(function(){
'use strict';
const C=window.QuoteConfig,KEY='fs-quote-config-demo-v1',$=s=>document.querySelector(s),app=$('#app');
if(new URLSearchParams(location.search).has('embed'))document.body.classList.add('embed');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>Number(x).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const clock=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
let state=C.seed(),round=C.round(),tab='rules',canEdit=true,edit=null,editId=null,auto=null,toastTimer,capInput='2000',failNext=false,hasCoords=true,merchant=C.SELF,pendingBid=null;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.schema===1&&saved.state?.policies){state=saved.state;round=saved.round||round;}}catch(_){}
const now=()=>new Date().toLocaleString('sv-SE');
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify({schema:1,state,round}));}catch(_){toast('浏览器无法保存，演示进度仅在当前页面保留。');}};
const enabled=()=>state.policies.find(p=>p.enabled);
const badge=(s,c='')=>`<span class="badge ${c}">${s}</span>`;
const rowsSummary=rows=>`<div class="stages-mini">${rows.map(r=>`<span>剩余 ${esc(r.minutes)} 分钟 → ${esc(r.percent)}%</span>`).join('')}</div>`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3200);}
function modal(title,body,footer=''){const d=$('#dialog');d.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="link" data-action="close" aria-label="关闭">✕</button></div><div class="dialog-body"><div id="error" class="error" role="alert"></div>${body}</div>${footer?`<div class="dialog-foot"><button data-action="close">取消</button>${footer}</div>`:''}`;if(!d.open)d.showModal();}
function error(text){if($('#dialog').open&&$('#error'))$('#error').textContent=text;else toast(text);}
function close(){edit=null;$('#dialog').close();}
function render(){document.querySelectorAll('[data-action="tab"]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));tab==='rules'?rules():demo();}
function rules(){const active=enabled();
app.innerHTML=`<section class="metrics"><div class="card metric"><div class="metric-label">当前生效策略</div><div class="metric-value">${active?esc(active.id):'暂无生效策略'} ${active?badge('v'+active.version,'blue'):''}</div><div class="sub">${active?'仅作用于新启动计划，历史计划保留原版本':'启用有效策略后，可启动阶梯报价'}</div></div><div class="card metric"><div class="metric-label">生效策略档位</div><div class="metric-value">${active?.rows.length||0}<span class="sub"> 档</span></div><div class="sub">按剩余时间逐步提高报价</div></div><div class="card metric"><div class="metric-label">最后一档出价比例</div><div class="metric-value">${active?'100%':'—'}</div><div class="sub">最高出价为操盘手授权上限</div></div></section>
<section class="card"><div class="card-head"><div><h2>自营阶梯报价策略</h2><div class="sub" style="margin-top:6px">本期统一使用一套生效策略，无需配置名称、备注或生效日期。</div></div><button class="primary" data-action="new" ${!canEdit?'disabled':''}>＋ 新建策略</button></div><div class="table-wrap"><table><thead><tr><th>规则编号 / 版本</th><th>阶梯明细</th><th>状态</th><th>更新人 / 时间</th><th>操作</th></tr></thead><tbody>${state.policies.map(p=>`<tr><td><b>${esc(p.id)}</b><div class="sub">v${p.version}</div></td><td>${rowsSummary(p.rows)}</td><td>${badge(p.enabled?'启用':'停用',p.enabled?'green':'')}</td><td>${esc(p.updatedBy)}<div class="sub">${esc(p.updatedAt)}</div></td><td><div class="actions"><button class="link" data-action="edit" data-id="${p.id}" ${!canEdit?'disabled':''}>编辑</button><button class="link" data-action="toggle" data-id="${p.id}" ${!canEdit?'disabled':''}>${p.enabled?'停用':'启用'}</button><button class="link" data-action="history" data-id="${p.id}">历史版本</button></div></td></tr>`).join('')}</tbody></table></div><div class="rule-foot"><span class="sub">共 ${state.policies.length} 套策略 · 仅允许一套启用</span><button class="link" data-action="tab" data-tab="demo">进入流程演示 →</button></div></section>
<div class="note" style="margin-top:18px">示例策略：剩余10分钟出85%、5分钟出95%、1分钟出100%。仅用于说明配置方式，不作为上线默认参数。</div>
<section class="explainer">${[['1','操盘手确认最高出价','先授权本轮报价上限，再按已启用策略逐档提交。'],['2','每档报价均可成交','卖家接受当前有效报价后，立即停止所有后续加价。'],['3','同一商家持续加价','报价记录真实追加，地图始终只更新同一自营商家点位。']].map(([i,t,d])=>`<div class="card card-body"><span class="step-num">${i}</span><div><h3>${t}</h3><p>${d}</p></div></div>`).join('')}</section>`;
}
function readRows(){return [...document.querySelectorAll('[data-row]')].map(row=>({minutes:row.querySelector('[data-field="minutes"]').value===''?NaN:Number(row.querySelector('[data-field="minutes"]').value),percent:row.querySelector('[data-field="percent"]').value===''?NaN:Number(row.querySelector('[data-field="percent"]').value)}));}
function drawRows(){const cap=Number($('#preview-cap')?.value||2000);$('#edit-rows').innerHTML=edit.map((r,i)=>`<tr data-row="${i}"><td>${i+1}</td><td><div class="input-unit"><input aria-label="第${i+1}档剩余时间" data-field="minutes" type="number" min="0" step="any" value="${Number.isFinite(r.minutes)?r.minutes:''}"><span>分钟</span></div></td><td><div class="input-unit"><input aria-label="第${i+1}档比例" data-field="percent" type="number" min="0" max="100" step="any" value="${Number.isFinite(r.percent)?r.percent:''}"><span>%</span></div></td><td class="preview-amount">${Number.isFinite(r.percent)?'MYR '+money(C.amount(cap,r.percent)):'—'}</td><td><button class="link" data-action="remove-row" data-index="${i}" ${edit.length===1?'disabled':''}>删除</button></td></tr>`).join('');}
function editor(id){const p=state.policies.find(x=>x.id===id);editId=id||null;edit=C.clone(p?.rows||C.initialRows());modal(p?'编辑策略':'新建策略',`<div class="note">时间从大到小、比例逐档递增，最后一档必须为100%。所有报价均来自同一家自营回收商。</div>${p?`<div class="sub" style="margin-top:16px">${p.id} · 当前 v${p.version}，保存为新版本并停用，检查后再启用。</div>`:''}<div class="table-wrap edit-table"><table><thead><tr><th>档位</th><th>竞拍剩余时间</th><th>最高出价比例</th><th>预计报价</th><th></th></tr></thead><tbody id="edit-rows"></tbody></table></div><button data-action="add-row">＋ 添加档位</button><div class="preview-row">预览最高出价 <input id="preview-cap" aria-label="预览最高出价" type="number" min="0.01" step="0.01" value="2000"> MYR</div><p class="sub">预计报价仅帮助检查配置；原型暂按两位小数四舍五入展示，正式取整口径待确认。预览金额不作为策略字段保存。</p>`,`<button class="primary" data-action="save">保存策略</button>`);drawRows();}
function map(){const latest=round.bids.at(-1),alive=round.remaining>0&&!round.settled;
return `<div class="map"><svg viewBox="0 0 900 400" preserveAspectRatio="none" role="img" aria-label="马来西亚吉隆坡区域示意地图"><rect width="900" height="400" fill="#e6f1f5"/><path d="M20 0H560L548 43 575 79 555 119 594 152 588 193 627 231 618 266 657 297 690 320 708 353 740 372 738 400H0V238L26 211 18 162 52 127 35 80Z" fill="#f5f5e9" stroke="#cbdccf" stroke-width="2"/><path d="M408 0L392 54 440 102 428 159 432 240 511 282 558 334 642 381" fill="none" stroke="#e8cfa0" stroke-width="5"/><path d="M218 0L258 59 303 110 317 171 389 220 432 240 512 204 577 160" fill="none" stroke="#e8dcb9" stroke-width="3"/><path d="M52 84L203 127 307 102 442 104 535 73M0 301L192 289 292 330 511 282 614 274" fill="none" stroke="#e1ddc1" stroke-width="2"/><path d="M0 58L900 58M0 159L900 159M0 259L900 259M0 360L900 360M149 0V400M349 0V400M550 0V400M751 0V400" stroke="#b9d4d5" stroke-opacity=".22" fill="none"/><path d="M459 129Q402 190 442 269T594 341" fill="none" stroke="#b8d9e4" stroke-width="4"/><text x="185" y="238" fill="#9bb8bf" font-size="16" letter-spacing="3">马六甲海峡</text><text x="655" y="150" fill="#9bb8bf" font-size="16" letter-spacing="3">南海</text><text x="464" y="269" fill="#728e86" font-size="13">吉隆坡 · Kuala Lumpur</text></svg><span class="map-label">马来西亚 · 地图示意</span>${latest&&hasCoords?`<span class="dot ${alive?'pulse':''}"></span><div class="map-pin"><div class="pin-name">FoneSquare 自营 ${badge('平台自营','green')}</div><div class="pin-price">MYR ${money(latest.price)}</div><div class="sub">吉隆坡 · 当前有效报价</div></div>`:`<div class="map-pin"><div class="pin-name">${latest?'商家位置暂不可用':'等待自营商家出价'}</div><div class="sub" style="margin-top:9px">${latest?'报价仍在下方列表展示':'出价成功后在地图展示'}</div></div>`}<span class="map-caption">示例坐标 3.1390° N, 101.6869° E · 非导航地图</span></div>`;
}
function progression(p){return `<div class="stage-progress">${p.policy.rows.map((r,i)=>{const bid=round.bids.find(b=>b.stage===i),lastError=round.errors.at(-1),isFailed=!bid&&i>p.lastStage&&lastError?.stage===i;let label=bid?'已出价 MYR '+money(bid.price):i<=p.lastStage?'已跳过':p.state==='running'?'待执行':p.state==='settled'?'成交后取消':p.state==='stopped'?'已停止':'本轮结束';return `<div class="progress-step ${bid?'done':isFailed?'failed':''}"><b>剩余 ${r.minutes} 分钟 · ${r.percent}%</b><div class="sub">${label}${isFailed&&p.state==='running'?' · 最近提交失败':''}</div></div>`;}).join('')}</div>`;}
function demo(){const p=round.plan,bid=round.bids.at(-1),done=round.settled,ended=round.remaining<=0,policy=enabled();
app.innerHTML=`<div class="demo-toolbar"><div class="clock"><small>本轮剩余时间</small><span id="clock-value">${clock(round.remaining)}</span> ${badge('演示时钟','blue')}</div><div class="actions"><button data-action="advance" ${done||ended?'disabled':''}>推进1分钟</button><button data-action="next" ${!p||p.state!=='running'||ended||done?'disabled':''}>到下一出价节点</button><button data-action="auto" ${done||ended?'disabled':''}>${auto?'暂停演示':'自动播放'}</button><button data-action="reset-round">重置演示</button></div></div>
<div class="demo-grid"><section class="card seller"><div class="seller-head"><div><strong>自营限时报价</strong><div class="sub" style="margin-top:7px">卖家视角 · 每次阶段报价均可接受成交</div></div>${badge(done?'已成交':ended?'竞拍结束':'竞拍中',done?'green':ended?'':'blue')}</div>${map()}<div class="bid-summary"><div class="bid-summary-top"><span>${done?'成交金额':'平台自营当前报价'}</span><span>已报价商家 <b>${bid?1:0}</b> 家</span></div><div class="big-price">${bid?'<small>MYR</small>'+money(done?done.bid.price:bid.price):'<span style="font-size:29px;color:#8aa79a;letter-spacing:0">暂无报价</span>'}</div><div class="accept-row"><div class="sub">${done?'已按卖家接受的报价成交，后续加价已停止。':ended?'本轮已结束，进入原有最终结果确认流程。':'接受当前有效报价后成交，不再等待下一档。'}</div><button class="green" data-action="accept" ${!bid||done||ended?'disabled':''}>${done?'已成交':'接受报价'}</button></div></div><div class="bid-stream"><h3>报价动态 <span class="sub">· 同一自营商家的真实出价记录</span></h3>${round.bids.length?round.bids.slice().reverse().map(b=>`<div class="bid-event"><div>FoneSquare 自营 ${badge('平台自营','green')}<div class="sub">${done?.bid.id===b.id?'卖家已接受该报价':'报价提交成功'}</div></div><strong>MYR ${money(b.price)}<div class="sub">出价时剩余 ${clock(b.remaining)}</div></strong></div>`).join(''):'<div class="empty">暂无成功出价记录</div>'}</div></section>
<aside class="card operator"><div class="card-head"><h2>操盘手控制台</h2>${badge('内部视角','blue')}</div><div class="card-body"><div class="mini-product"><span class="phone"></span><div><b>iPhone 15 Pro / 256GB</b><div class="sub">LOT-MY-DEMO-0216</div></div></div>
${p?`<div class="sub">已确认本轮最高出价</div><div class="cap"><small>MYR</small> ${money(p.cap)}</div><div class="sub">≈ CNY ${money(p.cap/.65)} · 演示汇率 0.65<br>${p.policy.id} / v${p.policy.version}</div>${progression(p)}<div class="note ${done?'green':p.state==='stopped'?'warn':''}" style="margin-top:18px">${done?'提前成交：MYR '+money(done.bid.price):p.state==='stopped'?'后续档位已停止，上一笔有效报价继续保留。':ended?'本轮已结束，不再提交报价。':'计划已锁定，配置更新不影响本轮。'}</div><div class="history-controls"><button class="danger" data-action="stop" ${p.state!=='running'||!canEdit?'disabled':''}>停止后续加价</button><button class="link" data-action="retry" ${p.state!=='running'||!canEdit?'disabled':''}>重试当前档</button></div>`:
`<label class="field">本轮最高出价（MYR）<input id="cap" inputmode="decimal" type="number" min="0.01" step="0.01" value="${esc(capInput)}" ${!canEdit?'disabled':''}></label><div class="sub" id="cap-cny">≈ CNY ${money(Number(capInput)/.65)} · 演示汇率 0.65</div><div class="field">生效策略<div style="margin-top:9px">${policy?esc(policy.id)+' / v'+policy.version:badge('暂无生效策略','orange')}</div></div>${policy?`<div class="stage-progress" id="cap-preview">${capPreview(policy)}</div>`:''}<div class="note">确认的是自动出价上限，不会直接将上限作为当前报价发布。</div><button class="primary" data-action="start" ${!policy||!canEdit||ended||merchant!==C.SELF?'disabled':''}>确认最高出价并启动</button>`}
${round.errors.length?`<div class="note warn" style="margin-top:18px">最近异常：${esc(round.errors.at(-1).message)}<br>失败不新增报价记录；关闭失败模拟后可重试。</div>`:''}
<details class="scenario"><summary>演示设置</summary><label><input type="checkbox" id="fail" ${failNext?'checked':''}>模拟报价提交失败</label><label><input type="checkbox" id="coords" ${hasCoords?'checked':''}>提供商家经纬度</label><label>账号 <select id="merchant" ${p?'disabled':''}><option value="${C.SELF}" ${merchant===C.SELF?'selected':''}>自营商家</option><option value="OTHER" ${merchant==='OTHER'?'selected':''}>其他回收商</option></select></label><p class="sub">自动播放：每1秒推进1分钟。刷新后保留进度，自动播放暂停。</p></details></div></aside></div>`;
}
function capPreview(p){const value=Number(capInput);return p.rows.map(r=>`<div class="progress-step"><b>剩余 ${r.minutes} 分钟 → ${r.percent}%</b><div class="sub">预计 MYR ${Number.isFinite(value)&&value>0?money(C.amount(value,r.percent)):'—'}</div></div>`).join('');}
function stopAuto(){clearInterval(auto);auto=null;}
function tick(seconds){C.advance(round,seconds,failNext);persist();if(round.settled||round.remaining<=0)stopAuto();if(tab==='demo')demo();}
const mutations=new Set(['new','edit','save','toggle','confirm-toggle','start','confirm-start','stop','confirm-stop','retry']);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;if(mutations.has(a)&&!canEdit)return;try{
 if(a==='close')return close();
 if(a==='tab'){tab=b.dataset.tab;if(tab!=='demo')stopAuto();render();return;}
 if(a==='new'||a==='edit'){editor(a==='edit'?id:null);return;}
 if(a==='add-row'){edit=readRows();edit.push({minutes:NaN,percent:NaN});drawRows();return;}
 if(a==='remove-row'){edit=readRows();edit.splice(Number(b.dataset.index),1);drawRows();return;}
 if(a==='save'){state=C.savePolicy(state,readRows(),editId,now());persist();close();rules();toast('已保存为停用版本，请检查后启用');return;}
 if(a==='toggle'){const p=state.policies.find(x=>x.id===id);modal(p.enabled?'停用策略':'启用策略',`<p>${p.enabled?'停用后不能再用该策略启动新计划。':'启用后，新计划将使用该策略。'}</p><div class="note">已启动计划保留原规则和最高价，不受本次变更影响。</div>`,`<button class="primary" data-action="confirm-toggle" data-id="${id}">确认${p.enabled?'停用':'启用'}</button>`);return;}
 if(a==='confirm-toggle'){state=C.togglePolicy(state,id,now());persist();close();render();return;}
 if(a==='history'){const p=state.policies.find(x=>x.id===id);modal('策略历史 · '+p.id,`<div class="history-row"><b>v${p.version} · 当前版本</b>${rowsSummary(p.rows)}<div class="sub">${p.updatedAt}</div></div>${p.history.slice().reverse().map(v=>`<div class="history-row"><b>v${v.version} · 历史快照</b>${rowsSummary(v.rows)}<div class="sub">${v.updatedAt}</div></div>`).join('')}<h3>维护记录</h3>${p.logs.slice().reverse().map(l=>`<div class="audit-row"><span>${esc(l.at)}</span>${esc(l.action)}</div>`).join('')}`);return;}
 if(a==='advance'){tick(60);return;}
 if(a==='next'){const next=round.plan.policy.rows.find(x=>x.minutes*60<round.remaining);tick(next?round.remaining-next.minutes*60:round.remaining);return;}
 if(a==='auto'){if(auto)stopAuto();else auto=setInterval(()=>tick(60),1000);demo();return;}
 if(a==='reset-round'){modal('重置演示进度','<p>清除本轮演示报价与成交记录，保留平台策略配置。</p>','<button class="primary" data-action="confirm-reset">确认重置</button>');return;}
 if(a==='confirm-reset'){stopAuto();round=C.round();failNext=false;merchant=C.SELF;persist();close();demo();return;}
 if(a==='start'){if(!Number.isFinite(Number(capInput))||Number(capInput)<=0)throw Error('请填写有效最高出价。');modal('确认最高出价并启动',`<p>本轮最高出价 <b>MYR ${money(capInput)}</b></p><div class="note">该金额为授权上限。各档会分别提交可成交的报价，卖家提前接受后即停止后续加价。</div><div class="stage-progress">${capPreview(enabled())}</div>`,'<button class="primary" data-action="confirm-start">确认启动</button>');return;}
 if(a==='confirm-start'){C.start(round,enabled(),Number(capInput),merchant);C.run(round,failNext);persist();close();demo();toast('计划已启动');return;}
 if(a==='stop'){modal('停止后续加价','<p>尚未执行的档位将停止。已提交的有效报价继续保留，卖家仍可接受。</p>','<button class="danger" data-action="confirm-stop">确认停止</button>');return;}
 if(a==='confirm-stop'){C.stop(round);stopAuto();persist();close();demo();return;}
 if(a==='retry'){C.run(round,failNext);persist();demo();return;}
 if(a==='accept'){const bid=round.bids.at(-1);pendingBid=bid.id;modal('确认接受当前报价',`<div class="sub">FoneSquare 自营 · iPhone 15 Pro / 256GB</div><div class="confirm-price"><small>MYR</small>${money(bid.price)}</div><div class="note green">将按此价格成交，后续加价立即停止。</div><p class="sub">当前为原型演示，不会创建真实交易。</p>`,'<button class="green" data-action="confirm-accept">确认接受并成交</button>');return;}
 if(a==='confirm-accept'){C.accept(round,pendingBid);stopAuto();persist();close();demo();toast('演示成交成功，后续加价已停止');return;}
}catch(err){error(err.message);}});
document.addEventListener('change',e=>{if(e.target.id==='permission'){canEdit=e.target.value==='edit';close();render();}if(e.target.id==='fail')failNext=e.target.checked;if(e.target.id==='coords'){hasCoords=e.target.checked;demo();}if(e.target.id==='merchant'){merchant=e.target.value;demo();}});
document.addEventListener('input',e=>{if(e.target.closest('[data-row]')||e.target.id==='preview-cap'){const cap=Number($('#preview-cap').value);document.querySelectorAll('[data-row]').forEach(r=>{const raw=r.querySelector('[data-field="percent"]').value,p=Number(raw);r.querySelector('.preview-amount').textContent=raw!==''&&Number.isFinite(cap)&&cap>0?'MYR '+money(C.amount(cap,p)):'—';});}if(e.target.id==='cap'){capInput=e.target.value;$('#cap-cny').textContent=Number(capInput)>0?'≈ CNY '+money(Number(capInput)/.65)+' · 演示汇率 0.65':'人民币参考金额：—';if($('#cap-preview'))$('#cap-preview').innerHTML=capPreview(enabled());}});
render();
})();
