(function () {
'use strict';
// Prototype-only session. No credentials are stored or sent to a server.
const KEY='fs-recycler-pc-session-demo-v1', screen=document.getElementById('auth-screen'), desk=document.getElementById('quote-workspace');
let lang='zh', tab='phone', method='phone', stage='login', region='', address='', dial='+60', password='', code='', consent=false, reveal=false, sentTo='', retryAt=0, tick;
const words={zh:{back:'返回原型首页',phoneTab:'手机',passTab:'密码',phone:'手机号码',email:'邮箱',switchEmail:'⇄ 邮箱',switchPhone:'⇄ 手机号码',phoneHint:'请输入手机号',emailHint:'请输入邮箱地址',password:'密码',passwordHint:'请输入密码',register:'注册',forgot:'忘记密码？',login:'登录',start:'登录 / 注册',agree:'继续即表示您同意我们的',terms:'服务条款',and:'和',privacy:'隐私政策',or:'或',emailLogin:'邮箱验证码登录',phoneLogin:'手机验证码登录',show:'显示密码',hide:'隐藏密码',code:'验证码',codeHint:'请输入6位验证码',send:'获取验证码',resend:'重新发送',verify:'验证并登录',verifyTitle:'验证您的账号',registerTitle:'注册账号',region:'国家/地区',regionHint:'请选择国家/地区',resetTitle:'找回密码',reset:'确认重置',newPassword:'新密码',passwordRule:'请设置至少6位密码',returnLogin:'返回登录',sent:'演示验证码为 123456，未发送真实短信或邮件。',wrongCode:'验证码不正确，请输入演示验证码 123456。',needCode:'请先获取验证码。',resetDone:'演示密码已重置，请使用密码登录。',footer:'交互原型：请使用示例账号，勿输入真实密码。',demo:'验证码 123456；密码可输入任意6位及以上字符。登录后进入自营演示工作台。',policy:'正式协议内容待接入，本原型不收集或提交账号资料。请勿填写真实密码。',close:'知道了',session:'演示登录仅在当前浏览器标签页生效。'},en:{back:'Back to prototypes',phoneTab:'Mobile',passTab:'Password',phone:'Mobile number',email:'Email',switchEmail:'⇄ Email',switchPhone:'⇄ Mobile',phoneHint:'Enter mobile number',emailHint:'Enter email address',password:'Password',passwordHint:'Enter password',register:'Register',forgot:'Forgot password?',login:'Sign in',start:'Sign in / Register',agree:'By continuing, you agree to our',terms:'Terms of Service',and:'and',privacy:'Privacy Policy',or:'or',emailLogin:'Sign in with email code',phoneLogin:'Sign in with mobile code',show:'Show password',hide:'Hide password',code:'Verification code',codeHint:'Enter 6-digit code',send:'Get code',resend:'Resend',verify:'Verify and sign in',verifyTitle:'Verify your account',registerTitle:'Create an account',region:'Country / Region',regionHint:'Select country / region',resetTitle:'Reset password',reset:'Reset password',newPassword:'New password',passwordRule:'Use at least 6 characters',returnLogin:'Back to sign in',sent:'Demo code: 123456. No SMS or email was sent.',wrongCode:'Incorrect code. Use the demo code 123456.',needCode:'Get a verification code first.',resetDone:'Demo password reset. Please sign in with a password.',footer:'Interactive prototype. Use sample details, not your real password.',demo:'Code: 123456. Password: any 6+ characters. Opens the internal demo workspace.',policy:'Official agreement content is not connected. This prototype does not collect or submit account details. Do not enter a real password.',close:'Got it',session:'Demo sign-in is only kept in this browser tab.'}};
const t=k=>words[lang][k], esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>{const paths={back:'<path d="m14 5-7 7 7 7"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M11 18h2"/>',eye:'<path d="M2 12s3-6 10-6 10 6 10 6-3 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',off:'<path d="m3 3 18 18M9 6.4A13 13 0 0 1 12 6c7 0 10 6 10 6a17 17 0 0 1-4 4M6 7.5A17 17 0 0 0 2 12s3 6 10 6a14 14 0 0 0 4-.6"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;};
const logo='<svg viewBox="0 0 186 126" role="img" aria-label="FoneSquare"><g fill="currentColor"><path d="M3 5h37v12H17v20h20v12H17v33H3zM48 5h38v77H48zm13 12v53h12V17zM94 5h13l18 45V5h13v77h-13l-18-45v45H94zM147 5h36v12h-23v19h20v12h-20v22h23v12h-36z"/><rect x="64" y="60" width="6" height="4" rx="2"/></g><text x="93" y="115" text-anchor="middle" fill="currentColor" font-family="monospace" font-size="31" letter-spacing="2">square</text></svg>';
function destination(){return method==='email'?address.trim().toLowerCase():dial+address.replace(/[\s-]/g,'');}
function validAddress(){const a=address.trim();return method==='email'?/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a):({'+60':/^0?1\d{8,9}$/,'+852':/^[2-9]\d{7}$/,'+86':/^1\d{10}$/,'+65':/^[689]\d{7}$/}[dial]).test(a.replace(/[\s-]/g,''));}
function needsCode(){return stage!=='login';}
function needsPassword(){return stage==='register'||stage==='reset'||stage==='login'&&tab==='password';}
function canSubmit(){return (stage!=='register'||['MY','HK'].includes(region))&&validAddress()&&consent&&(!needsPassword()||password.length>=6)&&(!needsCode()||/^\d{6}$/.test(code));}
function message(text){screen.querySelector('#auth-error').textContent=text;}
function sync(){screen.querySelector('#auth-submit').disabled=!canSubmit();const send=screen.querySelector('#auth-send');if(send){const left=sentTo===destination()?Math.max(0,Math.ceil((retryAt-Date.now())/1000)):0;send.disabled=!validAddress()||!consent||left>0;send.textContent=left?`${left}s`:t(sentTo===destination()?'resend':'send');}}
function render(){
clearInterval(tick);screen.lang=lang==='zh'?'zh-CN':'en';
const secondary=stage!=='login', title=stage==='verify'?t('verifyTitle'):stage==='register'?t('registerTitle'):t('resetTitle');
screen.innerHTML=`<div class="auth-top"><a class="auth-back" href="index.html">${icon('back')}${t('back')}</a><button class="auth-lang" type="button" data-auth="language" aria-label="${lang==='zh'?'Switch to English':'切换为简体中文'}">${icon('globe')}${lang==='zh'?'简':'EN'}</button></div>
<div class="auth-card"><div class="auth-brand">${logo}</div>${secondary?`<h1 class="auth-secondary-title">${title}</h1><p class="auth-subtitle">${stage==='verify'?esc((method==='phone'?dial+' ':'')+address):t('passwordRule')}</p>`:`<div class="auth-tabs" role="tablist" aria-label="${t('login')}"><button type="button" role="tab" data-auth="phone" aria-selected="${tab==='phone'}">${t(method==='email'&&tab==='phone'?'email':'phoneTab')}</button><button type="button" role="tab" data-auth="password" aria-selected="${tab==='password'}">${t('passTab')}</button></div>`}
<form id="auth-form" novalidate>${stage==='register'?`<div class="auth-field"><div class="auth-field-head"><label for="auth-region">${t('region')} <span aria-hidden="true" class="auth-required">*</span></label></div><div class="auth-input"><select id="auth-region" name="registrationRegion" required aria-required="true"><option value="">${t('regionHint')}</option>${[['MY','马来西亚','Malaysia'],['HK','中国香港','Hong Kong, China']].map(([value,zh,en])=>`<option value="${value}" ${region===value?'selected':''}>${lang==='zh'?zh:en}</option>`).join('')}</select></div></div>`:''}<div class="auth-field"><div class="auth-field-head"><label for="auth-address">${t(method==='email'?'email':'phone')}</label>${(stage==='register'||stage==='reset'||stage==='login'&&tab==='password')?`<button type="button" class="auth-link" data-auth="switch">${t(method==='email'?'switchPhone':'switchEmail')}</button>`:''}</div><div class="auth-input"><span class="auth-icon ${method==='email'?'mail':''}">${icon(method==='email'?'mail':'phone')}</span>${method==='phone'?`<select id="auth-dial" aria-label="${lang==='zh'?'国家或地区区号':'Country calling code'}" ${stage==='verify'?'disabled':''}>${['+60','+852','+86','+65'].map(d=>`<option ${dial===d?'selected':''}>${d}</option>`).join('')}</select>`:''}<input id="auth-address" name="account" type="${method==='email'?'email':'tel'}" autocomplete="username" placeholder="${t(method==='email'?'emailHint':'phoneHint')}" value="${esc(address)}" ${stage==='verify'?'readonly':''} maxlength="100" required></div></div>
${needsCode()?`<div class="auth-field"><div class="auth-field-head"><label for="auth-code">${t('code')}</label></div><div class="auth-input"><input id="auth-code" name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="${t('codeHint')}" value="${esc(code)}" required><button class="auth-code-send" id="auth-send" data-auth="send" type="button">${t('send')}</button></div></div>`:''}
${needsPassword()?`<div class="auth-field"><div class="auth-field-head"><label for="auth-password">${t(stage==='reset'?'newPassword':'password')}</label></div><div class="auth-input"><input id="auth-password" name="password" type="${reveal?'text':'password'}" autocomplete="${stage==='login'?'current-password':'new-password'}" placeholder="${t(stage==='login'?'passwordHint':'passwordRule')}" value="${esc(password)}" minlength="6" maxlength="128" required><button class="auth-eye" type="button" data-auth="eye" aria-label="${t(reveal?'hide':'show')}" aria-pressed="${reveal}">${icon(reveal?'eye':'off')}</button></div></div>`:''}
${!secondary&&tab==='password'?`<div class="auth-links"><button type="button" class="auth-link" data-auth="register">${t('register')}</button><button type="button" class="auth-link" data-auth="reset">${t('forgot')}</button></div>`:''}
<div id="auth-error" class="auth-message" role="status" aria-live="polite"></div><button id="auth-submit" type="submit" class="auth-submit" disabled>${t(stage==='reset'?'reset':stage==='register'?'register':stage==='verify'?'verify':tab==='phone'?'start':'login')}</button>
<div class="auth-consent"><input type="checkbox" id="auth-consent" ${consent?'checked':''} aria-labelledby="auth-consent-label"><span id="auth-consent-label"><label for="auth-consent">${t('agree')} </label><button type="button" class="auth-link" data-auth="terms">${t('terms')}</button> ${t('and')} <button type="button" class="auth-link" data-auth="privacy">${t('privacy')}</button></span></div>
</form>${secondary?`<div class="auth-divider"></div><button type="button" class="auth-link" data-auth="back">← ${t('returnLogin')}</button>`:`<div class="auth-divider">${t('or')}</div><button type="button" class="auth-email" data-auth="email" aria-label="${t(tab==='phone'&&method==='email'?'phoneLogin':'emailLogin')}">${icon(tab==='phone'&&method==='email'?'phone':'mail')}</button><p class="auth-other-label">${t(tab==='phone'&&method==='email'?'phoneLogin':'emailLogin')}</p>`}</div>
<footer class="auth-footer"><p>${t('footer')}</p><p>${t('demo')}</p></footer><dialog class="auth-policy" id="auth-policy" aria-labelledby="auth-policy-title"><h2 id="auth-policy-title"></h2><p>${t('policy')}</p><button type="button" data-auth="close">${t('close')}</button></dialog>`;
sync();if(needsCode())tick=setInterval(sync,1000);
}
function resetDelivery(){sentTo='';retryAt=0;code='';}
function sendCode(){if(!validAddress()||!consent)return;sentTo=destination();retryAt=Date.now()+60000;message(t('sent'));sync();}
function signedIn(){clearInterval(tick);try{sessionStorage.setItem(KEY,'signed-in');}catch(_){}password='';code='';screen.replaceChildren();screen.hidden=true;desk.hidden=false;desk.inert=false;document.title='报价工作台 · FoneSquare 回收商 PC';const main=document.getElementById('app');main.setAttribute('tabindex','-1');main.focus();}
function loggedOut(){try{sessionStorage.removeItem(KEY);}catch(_){}document.querySelector('[data-action="list"]').click();const modal=document.getElementById('modal');if(modal.open)modal.close();desk.hidden=true;desk.inert=true;screen.hidden=false;stage='login';tab='phone';method='phone';region='';password='';address='';consent=false;reveal=false;resetDelivery();render();document.title='账号登录 · FoneSquare 回收商 PC';screen.querySelector('#auth-address').focus();}
screen.addEventListener('input',e=>{if(e.target.id==='auth-address'){address=e.target.value;resetDelivery();}if(e.target.id==='auth-password')password=e.target.value;if(e.target.id==='auth-code')code=e.target.value;message('');sync();});
screen.addEventListener('change',e=>{if(e.target.id==='auth-region')region=e.target.value;if(e.target.id==='auth-consent')consent=e.target.checked;if(e.target.id==='auth-dial'){dial=e.target.value;resetDelivery();}sync();});
screen.addEventListener('click',e=>{const b=e.target.closest('[data-auth]');if(!b)return;const action=b.dataset.auth;
 if(action==='language'){lang=lang==='zh'?'en':'zh';render();return;}
 if(action==='eye'){reveal=!reveal;const input=screen.querySelector('#auth-password');input.type=reveal?'text':'password';b.innerHTML=icon(reveal?'eye':'off');b.setAttribute('aria-label',t(reveal?'hide':'show'));b.setAttribute('aria-pressed',String(reveal));return;}
 if(action==='terms'||action==='privacy'){screen.querySelector('#auth-policy-title').textContent=t(action);screen.querySelector('#auth-policy').showModal();return;}
 if(action==='close'){screen.querySelector('#auth-policy').close();return;}
 if(action==='send'){sendCode();return;}
 if(action==='phone'||action==='password'){tab=action;stage='login';if(action==='phone')method='phone';address='';password='';reveal=false;resetDelivery();}
 if(action==='switch'||action==='email'){method=action==='email'?(tab==='phone'&&method==='email'?'phone':'email'):(method==='email'?'phone':'email');address='';password='';reveal=false;resetDelivery();if(action==='email'){tab='phone';stage='login';}}
 if(action==='register'||action==='reset'){stage=action;region='';password='';reveal=false;resetDelivery();}
 if(action==='back'){stage='login';code='';password='';reveal=false;resetDelivery();}
 render();screen.querySelector('#auth-address').focus();
});
screen.addEventListener('submit',e=>{if(e.target.id!=='auth-form')return;e.preventDefault();if(!canSubmit())return;
 if(stage==='login'&&tab==='phone'){stage='verify';render();sendCode();screen.querySelector('#auth-code').focus();return;}
 if(needsCode()){if(sentTo!==destination()){message(t('needCode'));return;}if(code!=='123456'){message(t('wrongCode'));return;}}
 if(stage==='reset'){stage='login';tab='password';password='';code='';resetDelivery();render();message(t('resetDone'));return;}
 signedIn();
});
document.getElementById('auth-logout').addEventListener('click',loggedOut);
let hasSession=false;try{hasSession=sessionStorage.getItem(KEY)==='signed-in';}catch(_){}
if(hasSession){signedIn();}else{render();document.title='账号登录 · FoneSquare 回收商 PC';}
})();
