// Browser acceptance: serve the repository, set PROTOTYPE_BASE_URL and optional Playwright paths, then run with node.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,args:['--disable-gpu'],executablePath:process.env.CHROMIUM_PATH || undefined});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto((process.env.PROTOTYPE_BASE_URL || 'http://localhost:8771')+'/platform.html',{waitUntil:'domcontentloaded'});await p.evaluate(()=>{setView('store');openNewStoreModal()});assert.deepEqual(await p.locator('#newStoreBankMode option').evaluateAll(a=>a.map(n=>n.value)),['new','merchant']);assert.ok(!(await p.locator('#storeModal').innerText()).includes('复制'));await p.locator('#newStoreBankMode').selectOption('merchant');assert.equal(await p.locator('#newStoreBankSourceWrap').isVisible(),false);
 await p.screenshot({path:'/tmp/bank-nav-pc.png'});
 await p.goto((process.env.PROTOTYPE_BASE_URL || 'http://localhost:8771')+'/store.html',{waitUntil:'domcontentloaded'});await p.setViewportSize({width:430,height:932});await p.evaluate(()=>{roleSwitch.value='merchant';renderProfileScope();showPage('my')});
 assert.equal(await p.locator('#storeProfileScope').isVisible(),false);assert.equal(await p.locator('#storeAddressEntry').isVisible(),false);assert.equal(await p.locator('#bankAccountEntry').isVisible(),false);assert.equal(await p.locator('#merchantBankEntry').isVisible(),true);assert.equal(await p.locator('#storeManagementEntry').isVisible(),true);await p.screenshot({path:'/tmp/bank-nav-my.png'});
 await p.locator('#merchantBankEntry').click();for(const [bank,num] of [['Maybank','123456789012'],['CIMB','987654321012']]){await p.locator('#addAppMerchantBank').click();await p.locator('#appMerchant-holder').fill('FS Retail');await p.locator('#appMerchant-bankName').fill(bank);await p.locator('#appMerchant-accountNumber').fill(num);await p.locator('#saveAppMerchantBank').click();}
 const ids=await p.evaluate(()=>MerchantBanks.list('M1002').map(a=>a.id));await p.locator('#bankListBack').click();await p.locator('#storeManagementEntry').click();assert.equal(await p.locator('[data-manage-store]').count(),2);await p.locator('[data-manage-store="central"]').click();
 await p.locator('#managed-bankMode').selectOption('merchant');await p.locator('#managed-account').selectOption(ids[0]);assert.equal(await p.locator('#managed-number').isVisible(),false);await p.locator('#managed-phone').fill('+60 12-345 6789');await p.locator('#managed-name').fill('中心旗舰店');await p.locator('#managed-address-parts-state').fill('Selangor');await p.locator('#managed-address-parts-city').fill('Petaling Jaya');await p.locator('#managed-address-parts-postcode').fill('47810');await p.screenshot({path:'/tmp/bank-nav-edit.png',fullPage:true});await p.locator('#saveManagedStore').click();assert.equal(await p.evaluate(()=>MerchantBanks.selection('app:central').accountId),ids[0]);
 await p.locator('[data-manage-store="central"]').click();await p.locator('#managed-name').fill('Cancelled Name');await p.locator('#managed-account').selectOption(ids[1]);await p.locator('#storeEditBack').click();assert.equal(await p.evaluate(()=>storeProfiles[0].name),'中心旗舰店');assert.equal(await p.evaluate(()=>MerchantBanks.selection('app:central').accountId),ids[0]);
 await p.locator('[data-manage-store="central"]').click();await p.locator('#managed-account').selectOption(ids[1]);await p.locator('#saveManagedStore').click();assert.equal(await p.evaluate(()=>storeProfiles[0].bank.bankName),'CIMB');assert.equal(await p.evaluate(()=>storeProfiles[1].bank.bankName),'CIMB Bank');
 await p.locator('[data-manage-store="central"]').click();await p.locator('#managed-bankMode').selectOption('independent');await p.locator('#managed-holder').fill('Independent');await p.locator('#managed-bankName').fill('Public Bank');await p.locator('#managed-number').fill('333333333333');await p.locator('#saveManagedStore').click();assert.equal(await p.evaluate(()=>storeProfiles[0].bank.bankName),'Public Bank');assert.equal(await p.evaluate(()=>MerchantBanks.selection('app:central').accountId),null);
 await p.locator('#addManagedStore').click();await p.locator('#managed-name').fill('新增共享账户店铺');await p.locator('#managed-address-parts-state').fill('Selangor');await p.locator('#managed-address-parts-city').fill('Petaling Jaya');await p.locator('#managed-address-parts-postcode').fill('47810');await p.locator('#managed-address-parts-detail').fill('18, Jalan Teknologi 3/6');await p.locator('#managed-bankMode').selectOption('merchant');await p.locator('#saveManagedStore').click();assert.equal(await p.locator('#managed-error').isVisible(),true);assert.equal(await p.evaluate(()=>storeProfiles.length),2);await p.locator('#managed-account').selectOption(ids[0]);await p.locator('#saveManagedStore').click();assert.equal(await p.locator('[data-manage-store]').count(),3);assert.equal(await p.evaluate(()=>storeProfiles.at(-1).bank.bankName),'Maybank');
 await p.locator('#addManagedStore').click();await p.locator('#managed-name').fill('取消创建');await p.locator('#storeEditBack').click();assert.equal(await p.evaluate(()=>storeProfiles.length),3);
 await p.locator('#addManagedStore').click();await p.locator('#managed-name').fill('新增独立账户店铺');await p.locator('#managed-address-parts-state').fill('Selangor');await p.locator('#managed-address-parts-city').fill('Petaling Jaya');await p.locator('#managed-address-parts-postcode').fill('47810');await p.locator('#managed-address-parts-detail').fill('18, Jalan Teknologi 3/6');await p.locator('#managed-holder').fill('Independent New');await p.locator('#managed-bankName').fill('RHB');await p.locator('#managed-number').fill('444444444444');await p.locator('#saveManagedStore').click();assert.equal(await p.locator('[data-manage-store]').count(),4);assert.equal(await p.evaluate(()=>storeProfiles.at(-1).bank.bankName),'RHB');
 await p.reload({waitUntil:'domcontentloaded'});await p.evaluate(()=>{roleSwitch.value='merchant';renderProfileScope();showPage('my')});await p.locator('#storeManagementEntry').click();assert.equal(await p.locator('[data-manage-store]').count(),4);assert.equal(await p.evaluate(()=>storeProfiles.at(-2).bank.bankName),'Maybank');assert.equal(await p.evaluate(()=>storeProfiles.at(-1).bank.bankName),'RHB');await p.screenshot({path:'/tmp/bank-nav-list.png'});
 await p.evaluate(()=>{roleSwitch.value='employee';renderProfileScope();showPage('my')});assert.equal(await p.locator('#merchantBankEntry').isVisible(),false);assert.equal(await p.locator('#storeManagementEntry').isVisible(),false);assert.equal(await p.locator('#bankAccountEntry').isVisible(),true);await p.locator('#bankAccountEntry').click();assert.equal(await p.locator('#bankAccountHolder').inputValue(),'贾瑞真');
 await p.evaluate(()=>{roleSwitch.value='merchant';renderProfileScope();applyLanguage('en');showPage('my');renderProfileScope()});await p.locator('#storeManagementEntry').click();assert.ok((await p.locator('#managedStoresPage').innerText()).includes('Store Management'));await p.locator('[data-manage-store="central"]').click();assert.ok((await p.locator('#managedStoreEditPage').innerText()).includes('Select Merchant Account'));
 assert.deepEqual(errors,[]);console.log('PASS: PC only two account modes; App separate merchant/store entries; combined editor; read-only shared selection; cancel/switch/independent; employee isolation; English navigation; create store with shared/independent account; invalid/cancel create; reload persistence.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
