import test from 'node:test';
import assert from 'node:assert/strict';
import model from '../platform-account-model.js';
function fixture(){return model.create([{id:'A',merchantId:'F',type:'FoneSquare 回收商',status:'正常'},{id:'A',merchantId:'M',type:'供货商家',status:'正常',build:'开启'},{id:'B',merchantId:'N',type:'供货商家',status:'正常',build:'开启'}],[{id:'E',accountId:'C',merchantId:'M',relationStatus:'已关联',personalBuild:'开启'}],[{id:'S',merchantId:'M',status:'营业中'},{id:'T',merchantId:'M',status:'停用'}]);}
test('deduplicates App records and includes staff accounts',()=>{const m=fixture();assert.equal(m.accounts.size,3);assert.equal(m.role('C'),'店员');});
test('business disablement isolates Apps and preserves relationships and shop configuration',()=>{const m=fixture();m.setBusiness('M','停用','暂停');assert.equal(m.allowed('A','fs'),true);assert.equal(m.allowed('C','store'),false);assert.equal(m.effective(m.profile('C')),'商家已停用');assert.equal(m.profile('C').merchantId,'M');assert.deepEqual(m.stores.map(s=>s.status),['营业中','停用']);m.setBusiness('M','正常','恢复');assert.equal(m.allowed('C','store'),true);});
test('global disable invalidates both Apps; business enable does not override it',()=>{const m=fixture();m.setAccount('A','停用','全局');m.setBusiness('M','正常','恢复');assert.equal(m.allowed('A','fs'),false);assert.equal(m.allowed('A','store'),false);assert.equal(m.account('A').sessions.fs,2);});
test('handover keeps merchant/store identity and never swaps former primary into staff',()=>{const m=fixture();m.handover('M','C','交接');assert.equal(m.role('C'),'商家主账号');assert.equal(m.role('A'),'无有效身份');assert.equal(m.merchant('M').primaryAccountId,'C');assert.equal(m.stores[0].merchantId,'M');assert.equal(m.profile('C').roleActive,false);assert.equal(m.allowed('A','fs'),true);});
test('invalid reset and handover leave state unchanged',()=>{const m=fixture();assert.throws(()=>m.reset('A','重置'));assert.throws(()=>m.handover('M','B','交接'));assert.equal(m.logs.length,0);assert.equal(m.merchant('M').primaryAccountId,'A');});
test('orphan restore requires a legitimate successor and never recovers former role',()=>{const m=fixture();m.setBusiness('M','停用','退出');m.markClosed('M','已收尾');m.reset('A','结束身份');m.link('A','N','新工作');assert.throws(()=>m.setBusiness('M','正常','恢复'));assert.throws(()=>m.handover('M','A','恢复'));m.handover('M','C','接任');m.setBusiness('M','正常','恢复');assert.equal(m.role('A'),'店员');});
test('transfer requires reason, preserves bank and relationship history, resets target authorization',()=>{const m=fixture();const p=m.profile('C');p.bank={accountNumber:'123456789'};assert.throws(()=>m.link('C','N',''));assert.equal(p.merchantId,'M');m.link('C','N','调动');assert.equal(p.bank.accountNumber,'123456789');assert.equal(p.personalBuild,'关闭');assert.equal(p.relationHistory[0].merchantId,'M');});
test('unlink retains staff role; reset then new opening uses same account and new merchant',()=>{const m=fixture();m.unlink('C','离职');assert.equal(m.role('C'),'店员');m.reset('C','自己开店');m.openStoreBusiness('C',{name:'新商家',store:'新店',address:'KL',phone:'012',holder:'C',bankName:'Maybank',accountNumber:'123456789'},'开通');assert.equal(m.role('C'),'商家主账号');assert.notEqual(m.primary('C').merchantId,'M');assert.equal(m.accounts.size,3);assert.equal(m.profile('C').roleActive,false);});
