const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu']});const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await page.goto((process.env.PROTOTYPE_BASE_URL||'http://127.0.0.1:8794')+'/platform.html',{waitUntil:'networkidle'});
if(!await page.locator('[data-nav="mappingRule"]').isVisible()){await page.locator('#systemSwitch').click();await page.locator('[data-system-option="auction"]').click();}await page.locator('[data-nav="mappingRule"]').click();await page.locator('#mappingRulePage .pms-tabs').waitFor();
await page.screenshot({path:'/tmp/pms-mapping-list.png',fullPage:true});
await page.locator('[data-pms="preview"]').click();await page.locator('[data-pms="preview-run"]').click();assert.match(await page.locator('#pvOutput').innerText(),/OMAP-0002/);assert.match(await page.locator('#pvOutput').innerText(),/待补映射/);await page.screenshot({path:'/tmp/pms-mapping-preview.png'});await page.locator('[data-pms="close"]').first().click();
await page.locator('[data-pms="new"]').click();await page.locator('#pmName').fill('新增新加坡版本');await page.locator('#pmSourcePpn').selectOption('L2-REGION');assert.equal(await page.locator('#pmTargetPv').inputValue(),'');await page.locator('#pmSourcePv').selectOption('L2-SG');await page.locator('#pmTargetPpn').selectOption('L1-REGION');await page.locator('#pmTargetPv').selectOption('L1-CN');await page.locator('#pmReason').fill('补齐新加坡来源取价映射');await page.screenshot({path:'/tmp/pms-mapping-edit.png'});await page.locator('[data-pms="save"]').click();assert.equal(await page.locator('#pmsMappingDialog').isVisible(),false);
const row=page.locator('#pmsRuleResults tr').filter({hasText:'新增新加坡版本'});assert.match(await row.innerText(),/草稿/);await row.locator('[data-pms="enable"]').click();await page.locator('#pmLifecycleReason').fill('校验后启用');await page.locator('[data-pms="lifecycle-save"]').click();assert.match(await row.innerText(),/启用/);
await page.reload({waitUntil:'networkidle'});if(!await page.locator('[data-nav="mappingRule"]').isVisible()){await page.locator('#systemSwitch').click();await page.locator('[data-system-option="auction"]').click();}await page.locator('[data-nav="mappingRule"]').click();assert.match(await page.locator('#pmsRuleResults').innerText(),/新增新加坡版本/);
await page.locator('[data-pms="tab"][data-id="confirmation"]').click();await page.locator('[data-pms="draft-preview"]').click();await page.locator('[data-pms="preview-run"]').click();assert.match(await page.locator('#pvOutput').innerText(),/待人工确认/);assert.match(await page.locator('#pvOutput').innerText(),/马来版本/);await page.locator('[data-pms="close"]').first().click();
await page.locator('[data-pms="new"]').click();await page.locator('#pmSourcePpn').selectOption('L2-REGION');assert.equal(await page.locator('#pmCandidates option:checked').count(),0);await page.screenshot({path:'/tmp/pms-confirmation-edit.png'});await page.locator('[data-pms="close"]').first().click();
await page.locator('[data-pms="tab"][data-id="records"]').click();await page.locator('[data-pms="record"]').first().click();await page.locator('[data-pms="retry"]').click();assert.match(await page.locator('#pmsMappingDialog').innerText(),/待补映射/);await page.locator('[data-pms="reprocess"]').click();assert.match(await page.locator('#pmsMappingDialog').innerText(),/新配置/);await page.locator('[data-pms="reprocess-confirm"]').click();assert.match(await page.locator('#pmsMappingDialog h2').innerText(),/RUN-0002/);assert.doesNotMatch(await page.locator('#pmsMappingDialog .pms-version').allInnerTexts().then(t=>t.join(' ')),/待补映射/);await page.locator('[data-pms="close"]').first().click();
await page.locator('[data-pms="tab"][data-id="sources"]').click();await page.locator('[data-pms="sources-edit"]').click();await page.locator('#psPpn').selectOption('L2-CHANNEL');await page.locator('#psSelected').selectOption(['L2-RETAIL-MY']);await page.locator('#psReason').fill('维护来源集合');await page.locator('[data-pms="sources-save"]').click();assert.match(await page.locator('#pmsTabBody').innerText(),/购买渠道/);
await page.locator('#pmsPermission').selectOption('view');assert.equal(await page.locator('[data-pms="sources-edit"]').count(),0);await page.locator('[data-pms="tab"][data-id="mapping"]').click();assert.equal(await page.locator('[data-pms="new"]').count(),0);assert.equal(await page.locator('[data-pms="edit"]').count(),0);
await page.locator('#systemSwitch').click();await page.locator('[data-system-option="b2b"]').click();await page.locator('[data-nav="list"]').click();assert.equal(await page.locator('#listPage').isVisible(),true);await page.locator('[data-nav="store"]').click();assert.equal(await page.locator('#storePage').isVisible(),true);
// Existing global input decoration may leave an empty style attribute after dialogs.
const normalizeHtml=html=>html.replace(/ style=""/g,'');const storeHtml=normalizeHtml(await page.locator('#storePage').innerHTML());await page.locator('[data-nav="list"]').click();const listHtml=normalizeHtml(await page.locator('#listPage').innerHTML());
const baseline=await browser.newPage({viewport:{width:1600,height:1050}});await baseline.route('**/platform-pms-mapping.*',route=>route.abort());await baseline.goto((process.env.PROTOTYPE_BASE_URL||'http://127.0.0.1:8794')+'/platform.html',{waitUntil:'networkidle'});await baseline.locator('#systemSwitch').click();await baseline.locator('[data-system-option="auction"]').click();await baseline.locator('[data-nav="mappingRule"]').click();await baseline.locator('#systemSwitch').click();await baseline.locator('[data-system-option="b2b"]').click();await baseline.locator('[data-nav="list"]').click();await baseline.locator('[data-nav="store"]').click();assert.equal(normalizeHtml(await baseline.locator('#storePage').innerHTML()),storeHtml);await baseline.locator('[data-nav="list"]').click();assert.equal(normalizeHtml(await baseline.locator('#listPage').innerHTML()),listHtml);await baseline.close();
assert.deepEqual(errors,[]);console.log('PASS: mapping, confirmation, save/enable, persistence, snapshots, sources, permissions and unrelated navigation');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
