const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const base=process.env.PROTOTYPE_BASE_URL||'http://127.0.0.1:8795';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const close=()=>page.locator('#pmsMappingDialog [data-pms="close"]').first().click();
 const action=(id)=>page.locator(`[data-pms="${id}"]`);
 async function auction(p){if(!await p.locator('[data-nav="mappingRule"]').isVisible()){await p.locator('#systemSwitch').click();await p.locator('[data-system-option="auction"]').click();}await p.locator('[data-nav="mappingRule"]').click();}
 async function lot(p){await p.locator('[data-nav="bidList"]').click();await p.locator('[data-biz="view-bid"][data-id="LOT-MY-20260821-0216"]').first().click();await p.locator('[data-biz-tab="bid-snapshot"]').click();}
 async function extras(){await page.locator('[data-pms="tab"][data-id="extras"]').click();}
 async function newExtra(name,category='PHONE',attr='P2-CHANNEL',trigger='P2-OTHER'){
  await action('extra-new').click();await page.locator('#exName').fill(name);await page.locator('#exCategory').selectOption(category);await page.locator('#exAttribute').selectOption(attr);await page.locator('#exTrigger').selectOption(trigger);await action('extra-save').click();
 }
 try{
  await page.addInitScript(()=>{if(!localStorage.getItem('fs-pms-special-attributes-v1'))localStorage.setItem('fs-pms-special-attributes-v1','{"preserved":true}');});
  await page.goto(base+'/platform.html',{waitUntil:'networkidle'});await auction(page);
  assert.deepEqual(await page.locator('#mappingRulePage [role="tab"]').allTextContents(),['规则配置','附加属性值']);assert.equal(await page.locator('#pmsChannelFilter').count(),0);assert.equal(await page.locator('#pmsRuleResults tbody tr').count(),3);
  await extras();await newExtra('泰国版');let row=page.locator('[data-extra-code]').filter({hasText:'泰国版'});const thai=await row.getAttribute('data-extra-code');
  await newExtra('泰国版');assert.match(await page.locator('#pmsError').innerText(),/不能重复/);await close();
  await row.locator('[data-pms="extra-edit"]').click();await page.locator('#exName').fill('泰国版本');await action('extra-save').click();row=page.locator(`[data-extra-code="${thai}"]`);assert.match(await row.innerText(),/泰国版本/);
  await newExtra('临时附加值');const temp=page.locator('[data-extra-code]').filter({hasText:'临时附加值'}),tempCode=await temp.getAttribute('data-extra-code');await temp.locator('[data-pms="extra-delete"]').click();await action('extra-delete-confirm').click();assert.equal(await page.locator(`[data-extra-code="${tempCode}"]`).count(),0);
  const my=page.locator('[data-extra-code="EXT-00001"]');await my.locator('[data-pms="extra-delete"]').click();assert.match(await page.locator('#pmsMappingDialog').innerText(),/无法删除.*附加属性值/s);assert.match(await page.locator('#pmsMappingDialog').innerText(),/OMAP-0001 \/ V1/);assert.equal(await action('extra-delete-confirm').count(),0);await page.screenshot({path:'/tmp/pms-catalog-delete-blocked.png'});await close();
  await my.locator('[data-pms="extra-edit"]').click();assert.equal(await page.locator('#exCategory').isDisabled(),true);await page.locator('#exName').fill('马来版（新名称）');await action('extra-save').click();await page.screenshot({path:'/tmp/pms-catalog-list.png',fullPage:true});
  await page.locator('[data-pms="tab"][data-id="rules"]').click();let rule=page.locator('#pmsRuleResults tbody tr').filter({hasText:'OMAP-0002'});await rule.locator('[data-pms="edit"]').click();assert.equal(await page.locator('[data-detail-name],#pmChannelMode,#pmGroups').count(),0);assert.match(await page.locator('[data-detail-extra]').first().locator('option:checked').textContent(),/新名称/);const dm=page.locator('[data-detail-models]').first();assert.equal(await dm.locator('option:checked').textContent(),'全部支持型号');await dm.selectOption('101');await dm.selectOption(['__all','101']);assert.deepEqual(await dm.locator('option:checked').allTextContents(),['全部支持型号']);
  await action('detail-add').click();await page.locator('[data-detail-extra]').last().selectOption(thai);await page.locator('[data-detail-target]').last().selectOption('P1-CN');await page.locator('#pmReason').fill('从附加属性值列表选择并保存快照');await page.locator('#pmDetailRows').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/pms-catalog-rule.png'});await action('save').click();assert.match(await rule.innerText(),/草稿/);assert.match(await rule.innerText(),/当前生效 V1/);
  await rule.locator('[data-pms="history"]').click();assert.match(await page.locator('#pmsMappingDialog .pms-version').first().innerText(),/新名称/);assert.doesNotMatch(await page.locator('#pmsMappingDialog .pms-version').last().innerText(),/新名称/);await close();
  await extras();await page.locator(`[data-extra-code="${thai}"] [data-pms="extra-delete"]`).click();assert.match(await page.locator('#pmsMappingDialog').innerText(),/草稿/);await close();
  await newExtra('英国键盘布局','LAPTOP','N2-KEYBOARD','N2-OTHER');const uk=await page.locator('[data-extra-code]').filter({hasText:'英国键盘布局'}).getAttribute('data-extra-code');
  await page.locator('[data-pms="tab"][data-id="rules"]').click();await action('new').click();await page.locator('#pmCategory').selectOption('PHONE');await page.locator('#pmAttribute').selectOption('P2-CHANNEL');await page.locator('#pmTrigger').selectOption('P2-OTHER');assert.equal(await page.locator(`[data-detail-extra] option[value="${uk}"]`).count(),0);await page.locator('#pmCategory').selectOption('LAPTOP');assert.equal(await page.locator('#pmAttribute').inputValue(),'');await page.locator('#pmAttribute').selectOption('N2-KEYBOARD');await page.locator('#pmTrigger').selectOption('N2-OTHER');assert.equal(await page.locator('[data-detail-extra] option[value="EXT-00001"]').count(),0);assert.equal(await page.locator(`[data-detail-extra] option[value="${uk}"]`).count(),1);await close();
  await page.locator('#mappingRulePage [data-pms="preview"]').click();assert.equal(await page.locator('#pvChannel').count(),0);await action('preview-run').click();assert.match(await page.locator('#pvOutput').innerText(),/未选择/);await page.locator('[data-preview-extra="P2-OTHER"][data-group="actual"]').selectOption('EXT-00001');await page.locator('[data-preview-extra="P2-OTHER"][data-group="baseline"]').selectOption('EXT-00002');await action('preview-run').click();assert.match(await page.locator('#pvOutput').innerText(),/新加坡版/);assert.doesNotMatch(await page.locator('#pvOutput').innerText(),/停止该组取价/);await close();
  await lot(page);const published=await page.locator('#tab-bid-snapshot .snapshot-grid').innerHTML();assert.match(await page.locator('#tab-bid-snapshot').innerText(),/iPhone 15 Pro \/ 256GB \/ 马来版/);assert.doesNotMatch(await page.locator('#tab-bid-snapshot').innerText(),/新名称|PPV-MY-001/);assert.match(await page.locator('.pms-lot-conversion').innerText(),/取价映射值失效/);assert.match(await page.locator('.pms-lot-conversion').innerText(),/无需海外映射/);await page.screenshot({path:'/tmp/pms-lot-conversion.png',fullPage:true});
  assert.deepEqual(await page.locator('#tab-bid-snapshot .snapshot-item label').allTextContents(),['商品名称','一级商品名称','等级','MAX 原始报告','二级质检报告','一级质检报告']);assert.equal(await page.locator('#tab-bid-snapshot .pms-lot-history,#tab-bid-snapshot .pms-lot-conversion details,#tab-bid-snapshot [data-pms="record"]').count(),0);assert.doesNotMatch(await page.locator('#tab-bid-snapshot').innerText(),/最终展示语言|查看确认依据|MAX \/ PMS 冻结快照/);await page.screenshot({path:'/tmp/pms-lot-simplified.png',fullPage:true});
  const conversion=await page.locator('.pms-lot-conversion').innerHTML();
  const reportLink=kind=>page.locator(`[data-pms="inspection-report"][data-id="${kind}"]`),reportClose=()=>page.locator('#pmsInspectionDialog [data-report-close]').first().click();
  assert.equal(await page.locator('#tab-bid-snapshot .pms-report-tabs,#tab-bid-snapshot #pms-report-panel').count(),0);
  assert.deepEqual(await page.locator('#tab-bid-snapshot .pms-report-number').allTextContents(),['MAX-881920 / v4','PMS-240821-118','PJT-DEMO-001']);
  assert.equal(await reportLink('max').evaluate(e=>getComputedStyle(e).color),'rgb(22, 119, 255)');
  await reportLink('max').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#pmsInspectionDialog').isVisible(),true);assert.equal(await page.locator('#pms-report-panel .pms-inspection-item').count(),14);assert.match(await page.locator('#pms-report-panel').innerText(),/MAX 机检结果/);await page.keyboard.press('Escape');assert.equal(await page.locator('#pmsInspectionDialog').isVisible(),false);assert.equal(await reportLink('max').evaluate(e=>e===document.activeElement),true);
  for(const kind of ['secondary','primary']){await reportLink(kind).click();assert.equal(await page.locator('#pmsInspectionDialog').isVisible(),true);assert.equal(await page.locator('#pms-report-panel .pms-inspection-item').count(),31);assert.deepEqual(await page.locator('#pms-report-panel h4').allTextContents(),['成色描述','拆修情况','使用功能']);assert.match(await page.locator('#pms-report-panel .pms-report-meta').innerText(),new RegExp(kind==='primary'?'PJT-DEMO-001':'PMS-240821-118'));assert.equal(await page.locator('.pms-lot-conversion').innerHTML(),conversion);await reportClose();}
  await reportLink('primary').click();assert.match(await page.locator('#pms-report-panel').innerText(),/拍机堂质检标准/);await page.screenshot({path:'/tmp/pms-primary-report-detail.png',fullPage:true});await page.locator('#pms-report-panel .normal summary').click();assert.equal(await page.locator('#pms-report-panel .normal').getAttribute('open'),null);await page.locator('#pms-report-panel .normal summary').click();await reportClose();assert.equal(await page.locator('#tab-bid-snapshot .snapshot-grid').innerHTML(),published);
  await page.evaluate(()=>{const b=window.prototypeState.bids.find(b=>b.id==='LOT-MY-20260821-0216');b.inspectionReports={max:{number:'BROWSER-REPORT',groups:[{title:'功能检测',items:[{text:'触摸异常',status:'abnormal'},{text:'电池未检测',status:'unknown'},{text:'正常开机',status:'normal'}]}]}};});await reportLink('max').click();assert.equal(await page.locator('#pms-report-panel .pms-report-section').count(),3);assert.equal(await page.locator('#pms-report-panel .normal .pms-inspection-item').count(),1);assert.equal(await page.locator('#pms-report-panel .unknown .pms-inspection-item').count(),1);assert.equal(await page.locator('#pms-report-panel .abnormal .pms-inspection-item').count(),1);assert.equal(await page.locator('.pms-lot-conversion').innerHTML(),conversion);await reportClose();await page.evaluate(()=>delete window.prototypeState.bids.find(b=>b.id==='LOT-MY-20260821-0216').inspectionReports);
  const unrelatedTabs={};for(const id of ['bid-overview','bid-rounds','bid-decision','bid-log'])unrelatedTabs[id]=await page.locator('#tab-'+id).innerHTML();
  await page.reload({waitUntil:'networkidle'});await auction(page);await extras();assert.match(await page.locator('#pmsContent').innerText(),/泰国版本/);assert.equal(await page.evaluate(()=>localStorage.getItem('fs-pms-special-attributes-v1')),'{"preserved":true}');await page.locator('#pmsPermission').selectOption('view');assert.equal(await action('extra-new').count(),0);assert.equal(await action('extra-edit').count(),0);await lot(page);assert.equal(await page.locator('#tab-bid-snapshot .snapshot-grid').innerHTML(),published);assert.equal(await page.locator('#tab-bid-snapshot [data-pms="record"]').count(),0);
  // Compare only the untouched surfaces, including every other lot-detail tab.
  const norm=s=>s.replace(/ style=""/g,'');await page.locator('#systemSwitch').click();await page.locator('[data-system-option="b2b"]').click();await page.locator('[data-nav="list"]').click();await page.locator('[data-nav="store"]').click();const store=norm(await page.locator('#storePage').innerHTML());await page.locator('[data-nav="list"]').click();const list=norm(await page.locator('#listPage').innerHTML());
  const baseline=await browser.newPage({viewport:{width:1600,height:1100}});await baseline.route('**/platform-pms-mapping.*',r=>r.abort());await baseline.goto(base+'/platform.html',{waitUntil:'networkidle'});await auction(baseline);await lot(baseline);for(const [id,html] of Object.entries(unrelatedTabs))assert.equal(norm(await baseline.locator('#tab-'+id).innerHTML()),norm(html));await baseline.locator('#systemSwitch').click();await baseline.locator('[data-system-option="b2b"]').click();await baseline.locator('[data-nav="list"]').click();await baseline.locator('[data-nav="store"]').click();assert.equal(norm(await baseline.locator('#storePage').innerHTML()),store);await baseline.locator('[data-nav="list"]').click();assert.equal(norm(await baseline.locator('#listPage').innerHTML()),list);await baseline.close();
  assert.deepEqual(errors,[]);console.log('PASS: catalog CRUD/references, selector scope, immutable names, simplified lot display, persistence, permissions and untouched pages/tabs');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
