const {test}=require('node:test');const assert=require('node:assert/strict');const p=require('../platform-pms-mapping.js');
const copy=x=>JSON.parse(JSON.stringify(x));const now='2026-09-14T08:00:00Z';
const ctx=(actual=['L2-MY'],baseline=['L2-SG'])=>({country:'MY',channel:'STORE',model:'101',at:now,inputs:{actual,baseline}});
function draft(state,patch={}){return {...copy(state.rules[0].versions[0]),enabled:false,reason:'测试变更',...patch};}
test('two groups independently select lowest numeric priority and preserve the real input',()=>{const s=p.seed(),c=ctx(),snap=p.snapshot(s,c),r=p.evaluate(s,snap);assert.equal(r.actual.mapped[0].rule,'OMAP-0002 / V1');assert.equal(r.actual.mapped[0].targetPpn,'L1-REGION');assert.equal(r.baseline.status,'停止该组取价');assert.equal(c.inputs.actual[0],'L2-MY');assert.equal(r.actual.canRequestProductCode,false);});
test('normal second-level attributes remain for PMS conversion, not treated as first-level',()=>{const s=p.seed(),r=p.evaluate(s,p.snapshot(s,ctx(['L2-RETAIL-CN'],['L2-MY'])));assert.equal(r.actual.remaining[0].standard,'JDX-L2');assert.equal(r.actual.mapped.length,0);});
test('generic source requires manual confirmation and only valid concrete candidates are offered',()=>{const s=p.seed(),snap=p.snapshot(s,ctx(['L2-OTHER']));const r=p.confirmation(snap,'L2-OTHER');assert.equal(r.status,'待人工确认');assert.deepEqual(r.candidates,['L2-MY','L2-SG']);assert.equal(p.evaluate(s,snap).actual.status,'停止该组取价');assert.equal(p.confirmation(snap,'L2-MY').status,'无需人工确认');});
test('draft is saved despite overlap, but activation locates the conflicting rule',()=>{const s=p.seed(),v=draft(s,{priority:10,models:['101']});const r=p.saveRule(s,v,null,null);assert.equal(p.status(p.latest(r)),'草稿');assert.throws(()=>p.enableRule(s,r.id,1,r.revision,'启用','maintain',now),/OMAP-0002/);});
test('different priorities may overlap; tied runtime rules stop without random choice',()=>{const s=p.seed(),v=draft(s,{priority:5,models:['101']});const r=p.saveRule(s,v);p.enableRule(s,r.id,1,r.revision,'启用','maintain',now);assert.equal(p.evaluate(s,p.snapshot(s,ctx())).actual.mapped[0].priority,5);const snap=p.snapshot(s,ctx());snap.rules.push({...copy(snap.rules.find(x=>x.priority===5)),id:'BAD-DUP'});assert.match(p.evaluate(s,snap).actual.errors.join(),/并列/);});
test('editing and scheduled activation preserve the current version until the new effective instant',()=>{const s=p.seed(),r=s.rules[0],v=draft(s,{name:'未来版本',start:'2026-10-01T00:00:00+08:00'});p.saveRule(s,v,r.id,r.revision);assert.equal(p.active(r,Date.parse(now)).version,1);p.enableRule(s,r.id,2,r.revision,'定时启用','maintain',now);assert.equal(p.active(r,Date.parse(now)).version,1);assert.equal(p.active(r,Date.parse('2026-10-02T00:00:00Z')).version,2);p.disableRule(s,r.id,r.revision,'停用','maintain',now);assert.equal(p.active(r,Date.parse('2026-10-02T00:00:00Z')),undefined);assert.equal(s.sourceSets[0].values.includes('L2-MY'),true);});
test('old snapshots and retry retain original rule versions; new processing creates related record',()=>{const s=p.seed(),old=copy(s.records[0].snapshot),r=s.rules[0];p.saveRule(s,draft(s,{priority:80}),r.id,r.revision);p.retryRecord(s,'RUN-0001');assert.deepEqual(s.records[0].snapshot,old);const next=p.reprocess(s,'RUN-0001');assert.equal(next.parentId,'RUN-0001');assert.notEqual(next.id,'RUN-0001');assert.equal(s.records.length,2);assert.deepEqual(s.records[1].snapshot,old);next.frozen=true;assert.throws(()=>p.retryRecord(s,next.id),/冻结/);});
test('read-only and stale concurrent writes are rejected by model mutations',()=>{const s=p.seed();assert.throws(()=>p.saveRule(s,draft(s),null,null,'view'),/查看权限/);const r=s.rules[0],rev=r.revision;p.saveRule(s,draft(s),r.id,rev);assert.throws(()=>p.saveRule(s,draft(s),r.id,rev),/刷新/);assert.throws(()=>p.saveSources(s,'MY','L2-REGION',['L2-MY'],'变更',0),/刷新/);});
test('target must be first-level for same business attribute and fit model scope',()=>{const s=p.seed();assert.match(p.validate(s,draft(s,{targetPpn:'L1-CHANNEL',targetPpv:'L1-RETAIL-CN'})),/同一业务属性/);assert.match(p.validate(s,draft(s,{targetPpv:'L1-INTL'}),true),/不支持/);});
test('invalid winning target does not fall back to another valid lower-priority rule',()=>{const s=p.seed(),snap=p.snapshot(s,ctx());snap.rules.find(v=>v.id==='OMAP-0002').targetPpv='MISSING';const r=p.evaluate(s,snap);assert.equal(r.actual.mapped.length,0);assert.match(r.actual.errors.join(),/不回退/);});
test('conflicting values for one target attribute halt that group',()=>{const s=p.seed(),snap=p.snapshot(s,ctx(['L2-MY','L2-HK']));snap.rules.push({...copy(snap.rules[0]),id:'HK',sourcePvIds:['L2-HK'],targetPpv:'L1-INTL'});assert.match(p.evaluate(s,snap).actual.errors.join(),/冲突值/);});
test('date ranges are left closed and right open; overlapping channels and models are explicit',()=>{const s=p.seed(),v=draft(s,{models:['201'],channels:['PARTNER'],priority:10,end:'2030-01-01T00:00:00Z'});assert.equal(p.validate(s,v,true),'');assert.equal(p.status({...v,enabled:true},Date.parse(v.end)),'已过期');});
test('a stopped rule does not block later activation due to a past configured start',()=>{const s=p.seed();p.disableRule(s,'OMAP-0001',1,'停用','maintain','2026-09-14T07:30:00Z');const r=p.saveRule(s,draft(s));p.enableRule(s,r.id,1,r.revision,'替代','maintain',now);assert.equal(p.active(r,Date.parse(now)).version,1);assert.equal(p.active(r,Date.parse('2026-09-14T07:45:00Z')),undefined);});
test('historical previews select the source collection version at their execution time',()=>{const s=p.seed(),set=s.sourceSets[0];set.history=[copy({...set,history:undefined})];Object.assign(set,{version:2,values:['L2-MY'],updatedAt:'2026-09-14T09:00:00Z'});const snap=p.snapshot(s,ctx());assert.equal(snap.sourceSets[0].version,1);assert.equal(p.evaluate(s,snap).baseline.status,'停止该组取价');});
