const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM,VirtualConsole}=require(process.env.JSDOM_MODULE||'jsdom');
(async()=>{const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=await JSDOM.fromURL((process.env.PROTOTYPE_BASE_URL||'http://127.0.0.1:8796')+'/platform.html',{resources:'usable',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};}});await new Promise(r=>dom.window.addEventListener('load',r));const w=dom.window,d=w.document,q=s=>{const n=d.querySelector(s);assert.ok(n,'Missing '+s);return n;},click=s=>q(s).click(),value=(s,v)=>{q(s).value=v;q(s).dispatchEvent(new w.Event('change',{bubbles:true}));},state=()=>w.prototypeState.pmsMapping.getState(),ruleAction=a=>click(`#pmsMappingDialog [data-pms="${a}"]`),extraAction=a=>click(`#pmsExtraDialog [data-extra-action="${a}"]`);
try{
 click('#systemSwitch');click('[data-system-option="auction"]');w.setView('mappingRule');const reports=JSON.stringify(state().publications),original=JSON.stringify(state().rules);
 click('[data-pms="tab"][data-id="extras"]');click('#mappingRulePage [data-pms="extra-new"]');assert.equal(d.querySelectorAll('#pmsExtraDialog input').length,1);assert.equal(d.querySelectorAll('#exCategory,#exTrigger,#exCountry,#exCode').length,0);extraAction('save');assert.match(q('#pmsExtraError').textContent,/先选择二级/);value('#exAttribute','P2-CHANNEL');value('#exName','泰国版');extraAction('save');assert.equal(q('#pmsExtraDialog').open,false);const thai=state().extraCatalog.find(x=>x.name==='泰国版');assert.ok(thai);assert.equal(thai.sourcePpn,'P2-CHANNEL');
 click('#mappingRulePage [data-pms="extra-new"]');value('#exAttribute','P2-CHANNEL');value('#exName','泰国版');extraAction('save');assert.match(q('#pmsExtraError').textContent,/不能重复/);extraAction('close');
 click('[data-extra-code="EXT-00001"] [data-pms="extra-delete"]');assert.match(q('#pmsMappingDialog').textContent,/无法删除/);assert.equal(d.querySelector('[data-pms="extra-delete-confirm"]'),null);ruleAction('close');
 click('[data-extra-code="EXT-00001"] [data-pms="extra-edit"]');value('#exName','马来版更新名称');extraAction('save');assert.equal(JSON.stringify(state().rules),original);assert.equal(JSON.stringify(state().publications),reports);
 click('[data-pms="tab"][data-id="rules"]');click('#mappingRulePage [data-pms="new"]');assert.equal(d.querySelectorAll('#pmCountry,#pmStandards,#pmPrompt,#pmId,#pmStatus,#pmName,#pmReason,#pmStart,#pmEnd,[data-detail-models]').length,0);assert.equal(q('#pmEnabled').value,'disabled');assert.match(q('#pmAttribute').parentElement.textContent,/^属性项/);assert.equal(d.querySelector('#pmTargetAttribute'),null);assert.equal(q('[data-detail-trigger]').textContent,'—');assert.equal(d.querySelectorAll('#mappingRulePage [data-pms="preview"],#mappingRulePage [data-pms="version-preview"]').length,0);
 value('#pmCategory','PHONE');value('#pmAttribute','P2-CHANNEL');value('#pmTrigger','P2-OTHER');assert.equal(q('[data-detail-target]').disabled,false);assert.equal(d.querySelector('#pmTargetAttribute'),null);assert.equal(q('[data-detail-trigger]').textContent,'其他版本');assert.ok(q('#pmConfirmMode option[value="direct"]').disabled);value('#pmPriority','65');value('[data-detail-extra]',thai.code);value('[data-detail-target]','P1-CN');const first=q('[data-detail-target]');assert.ok([...first.options].filter(x=>x.value).every(x=>x.value.startsWith('P1-')));
 ruleAction('extra-inline-new');assert.equal(q('#pmsMappingDialog').open,true);assert.equal(d.querySelectorAll('#pmsExtraDialog input').length,1);value('#exName','取消的值');extraAction('close');assert.equal(q('[data-detail-extra]').value,thai.code);assert.equal(q('[data-detail-target]').value,'P1-CN');assert.equal(q('#pmPriority').value,'65');assert.equal(state().extraCatalog.some(x=>x.name==='取消的值'),false);
 ruleAction('extra-inline-new');value('#exName','欧洲版');extraAction('save');const euro=state().extraCatalog.find(x=>x.name==='欧洲版');assert.equal(q('[data-detail-extra]').value,euro.code);assert.equal(q('[data-detail-target]').value,'P1-CN');assert.equal(q('#pmPriority').value,'65');assert.equal(q('#pmsMappingDialog').open,true);assert.equal(JSON.stringify(state().rules),original);
 ruleAction('save');assert.equal(q('#pmsMappingDialog').open,false);const saved=state().rules.find(r=>r.id==='OMAP-0004').versions.at(-1);assert.equal(saved.targetPpn,'P1-CHANNEL');assert.equal(saved.details[0].targetPpv,'P1-CN');assert.equal(saved.details[0].code,euro.code);assert.equal(saved.priority,65);
 click('#mappingRulePage [data-pms="new"]');value('#pmCategory','PHONE');value('#pmAttribute','P2-CHANNEL');value('#pmTrigger','P2-CN');value('#pmConfirmMode','direct');assert.equal(q('[data-detail-trigger]').textContent,'大陆国行');assert.equal(d.querySelectorAll('[data-detail-extra]').length,0);value('[data-detail-target]','P1-CN');ruleAction('save');assert.equal(q('#pmsMappingDialog').open,false);
 click('#mappingRulePage [data-pms="new"]');value('#pmCategory','PHONE');value('#pmAttribute','P2-CHANNEL');value('#pmTrigger','P2-OTHER');value('#pmConfirmMode','direct');assert.equal(q('#pmConfirmMode').value,'extra');value('[data-detail-extra]',euro.code);value('[data-detail-target]','P1-CN');value('#pmCategory','LAPTOP');assert.equal(q('#pmAttribute').value,'');assert.equal(q('[data-detail-target]').value,'');value('#pmAttribute','N2-KEYBOARD');value('#pmTrigger','N2-OTHER');assert.equal([...q('[data-detail-extra]').options].some(x=>x.value===euro.code),false);assert.ok([...q('[data-detail-target]').options].filter(x=>x.value).every(x=>x.value.startsWith('N1-')));ruleAction('close');
 click('#mappingRulePage [data-pms="edit"][data-id="OMAP-0001"]');assert.equal(d.querySelectorAll('[data-detail-models]').length,0);assert.equal(q('#pmEnabled').value,'enabled');value('#pmAttribute','P2-COLOR');assert.equal(q('[data-detail-target]').value,'');assert.ok([...q('[data-detail-target]').options].some(x=>x.value==='P1-BLACK'));ruleAction('close');
 click('#mappingRulePage [data-pms="enable"][data-id="OMAP-0004"]');ruleAction('lifecycle-save');assert.equal(q('#pmsMappingDialog').open,false);assert.ok(w.PmsMapping.active(state().rules.find(r=>r.id==='OMAP-0004')));click('#mappingRulePage [data-pms="disable"][data-id="OMAP-0004"]');ruleAction('lifecycle-save');assert.equal(w.PmsMapping.active(state().rules.find(r=>r.id==='OMAP-0004')),undefined);

 click('#mappingRulePage [data-pms="tab"][data-id="extras"]');click('[data-extra-code="'+thai.code+'"] [data-pms="extra-delete"]');ruleAction('extra-delete-confirm');assert.ok(state().extraCatalog.find(x=>x.code===thai.code).deletedAt);assert.equal(JSON.stringify(state().publications),reports);
 value('#pmsPermission','view');assert.equal(d.querySelectorAll('#mappingRulePage [data-pms="extra-new"],#mappingRulePage [data-pms="extra-edit"]').length,0);
 for(const view of ['report2Rule','priceManagement','bidList','financeLedger','store']){w.setView(view);assert.ok(q('#'+view+'Page').classList.contains('active'));}assert.deepEqual(errors,[]);
 w.setView('mappingRule');value('#pmsPermission','maintain');click('[data-pms="tab"][data-id="rules"]');click('#mappingRulePage [data-pms="edit"][data-id="OMAP-0001"]');fs.writeFileSync('/tmp/pms-rule-ux-snapshot.html',dom.serialize().replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''));
 console.log('PASS: secondary-scoped extras, primary attribute/value cascade, inline draft preservation, immediate enable/disable, removed fields/previews, frozen history, unrelated views');
}finally{w.close();}})().catch(e=>{console.error(e);process.exit(1)});
