const {test}=require('node:test');const assert=require('node:assert/strict');const p=require('../platform-pms-mapping.js');
const at='2026-09-14T12:00:00Z';
const ctx=(actual=[{ppv:'P2-OTHER',extraCode:'EXT-00001'}],baseline=[{ppv:'P2-OTHER',extraCode:'EXT-00002'}])=>({category:'PHONE',country:'MY',model:'101',at,inputs:{actual,baseline}});
const newExtra=(s,name)=>p.saveExtra(s,{name});
const draft=(s,patch={})=>({...p.clone(p.latest(s.rules[0])),reason:'测试变更',...patch});
test('Malaysia is an overseas extra, not a PMS secondary PPV; unified version owns every detail',()=>{const s=p.seed();assert.equal(p.source('EXT-00001'),undefined);assert.equal(p.attributes.filter(a=>a.category==='PHONE').flatMap(a=>a.values).some(v=>v.name==='马来版'),false);const r=p.saveRule(s,draft(s,{priority:80}),s.rules[0].id,s.rules[0].revision);assert.equal(p.latest(r).version,3);assert.equal(p.latest(r).details.length,2);assert.equal(p.active(r,Date.parse(at)).version,2);});
test('two groups independently select extra rows within the same highest-priority rule',()=>{const s=p.seed(),c=ctx(),r=p.evaluate(s,p.snapshot(s,c));assert.equal(r.actual.mapped[0].rule,'OMAP-0002 / V1');assert.equal(r.baseline.mapped[0].rule,'OMAP-0002 / V1');assert.equal(r.actual.mapped[0].extraName,'马来版');assert.equal(r.baseline.mapped[0].extraName,'新加坡版');assert.equal(c.inputs.actual[0].ppv,'P2-OTHER');assert.equal(r.actual.canRequestProductCode,false);});
test('single candidate still needs explicit selection; choices are chosen before target validation',()=>{const s=p.seed(),snap=p.snapshot(s,ctx());snap.rules.find(v=>v.id==='OMAP-0002').details=[{code:'EXT-00001',name:'马来版',targetPpv:'MISSING',models:[]}];assert.equal(p.confirmation(snap,{ppv:'P2-OTHER'}).status,'待人工确认');assert.equal(p.confirmation(snap,{ppv:'P2-OTHER',extraCode:'EXT-00001'}).status,'已确认');const r=p.evaluate(s,snap);assert.match(r.actual.errors.join(),/失效/);assert.equal(r.actual.items[0].confirmationComplete,true);});
test('same-priority overlap cannot be enabled even with different extra choices',()=>{const s=p.seed(),v=draft(s,{priority:10,details:[{code:newExtra(s,'欧洲版').code,name:'欧洲版',targetPpv:'P1-CN',models:[]}]});const r=p.saveRule(s,v);assert.throws(()=>p.enableRule(s,r.id,1,r.revision,'启用','maintain',at),/OMAP-0002.*附加选项不同/);assert.equal(p.latest(r).details[0].code.startsWith('EXT-'),true);});
test('winning rule never borrows a detail from a lower-priority rule',()=>{const s=p.seed(),snap=p.snapshot(s,ctx());snap.rules.find(v=>v.id==='OMAP-0002').details=snap.rules.find(v=>v.id==='OMAP-0002').details.filter(d=>d.code!=='EXT-00002');const r=p.evaluate(s,snap);assert.equal(r.actual.errors.length,0);assert.match(r.baseline.errors.join(),/不回退其他规则/);});
test('phone and laptop dictionaries and model scopes cannot cross',()=>{const s=p.seed();assert.match(p.validate(s,draft(s,{category:'LAPTOP'})),/标准与品类/);assert.match(p.validate(s,draft(s,{models:['301']})),/跨品类/);const c={...ctx(),category:'LAPTOP',model:'301'};assert.match(p.evaluate(s,p.snapshot(s,c)).actual.errors.join(),/品类/);const n={...c,inputs:{actual:[{ppv:'N2-OTHER',extraCode:'EXT-00003'}],baseline:[{ppv:'N2-CN'}]}};assert.equal(p.evaluate(s,p.snapshot(s,n)).actual.mapped[0].targetPpv,'N1-US');});
test('detail models must fit parent scope and offer a candidate to each applicable model',()=>{const s=p.seed();assert.match(p.validate(s,draft(s,{models:['101'],details:[{code:'EXT-00001',name:'马来版',models:['102'],targetPpv:'P1-CN'}]})),/不能超出/);assert.match(p.validate(s,draft(s,{details:[{code:'EXT-00001',name:'马来版',models:['101'],targetPpv:'P1-CN'}]}),true,'OMAP-0001',Date.parse(at)),/没有有效/);});
test('duplicate extras, missing targets and mixed empty details are rejected',()=>{const s=p.seed();const v=draft(s);v.details[1].code=v.details[0].code;assert.match(p.validate(s,v),/重复/);assert.match(p.validate(s,draft(s,{details:[{code:'EXT-00001',name:'马来版',targetPpv:'',models:[]}]})),/每行须选择/);assert.match(p.validate(s,draft(s,{details:[...draft(s).details,{code:'',name:'',targetPpv:'P1-CN',models:[]}]})),/不能混用/);});
test('direct mapping only permits concrete source, and normal attributes stay in secondary conversion input',()=>{const s=p.seed(),direct={code:'',name:'',models:[],targetPpv:'P1-CN'};assert.match(p.validate(s,draft(s,{details:[direct]})),/必须配置具体/);const r=p.saveRule(s,draft(s,{triggerPpv:'P2-CN',details:[direct]}));p.enableRule(s,r.id,1,r.revision,'启用','maintain',at);const result=p.evaluate(s,p.snapshot(s,ctx([{ppv:'P2-CN'},{ppv:'P2-BLACK'}])));assert.equal(result.actual.mapped[0].targetPpv,'P1-CN');assert.equal(result.actual.remaining[0].ppv,'P2-BLACK');});
test('editing and scheduled activation replace every detail atomically; disabling keeps coverage',()=>{const s=p.seed(),r=s.rules[0];p.saveRule(s,draft(s,{start:'2026-10-01T00:00:00Z'}),r.id,r.revision);p.enableRule(s,r.id,3,r.revision,'定时启用','maintain',at);assert.equal(p.active(r,Date.parse(at)).version,2);assert.equal(p.active(r,Date.parse('2026-10-02')).version,3);const count=s.coverage.length;p.disableRule(s,r.id,r.revision,'停用','maintain',at);assert.equal(p.active(r,Date.parse('2026-10-02')),undefined);assert.equal(s.coverage.length,count);});
test('old retry uses original input and snapshot; new processing links a new record using both groups',()=>{const s=p.seed(),before=p.clone(s.records[0]);p.retryRecord(s,'RUN-0001');assert.deepEqual(s.records[0].snapshot,before.snapshot);assert.match(s.records[0].result.actual.errors.join(),/失效/);const next=p.reprocess(s,'RUN-0001','maintain',at);assert.equal(next.parentId,'RUN-0001');assert.equal(next.result.actual.errors.length,0);assert.deepEqual(next.context.inputs,before.context.inputs);assert.equal(s.records[1].snapshot.rules[0].version,1);next.frozen=true;assert.throws(()=>p.retryRecord(s,next.id),/冻结/);});
test('permissions, optimistic concurrency and one pending version are enforced',()=>{const s=p.seed(),r=s.rules[0],rev=r.revision;assert.throws(()=>p.saveRule(s,draft(s),r.id,rev,'view'),/查看权限/);p.saveRule(s,draft(s,{start:'2026-10-01T00:00:00Z'}),r.id,rev);assert.throws(()=>p.saveRule(s,draft(s),r.id,rev),/刷新/);p.enableRule(s,r.id,3,r.revision,'排期','maintain',at);p.saveRule(s,draft(s,{start:'2026-11-01T00:00:00Z'}),r.id,r.revision);assert.throws(()=>p.enableRule(s,r.id,4,r.revision,'再排期','maintain',at),/已有待生效/);});
test('runtime priority ties stop before choosing extras; date boundaries exclude the end',()=>{const s=p.seed(),snap=p.snapshot(s,ctx());snap.rules.push({...p.clone(snap.rules.find(r=>r.id==='OMAP-0002')),id:'DUP'});assert.match(p.confirmation(snap,{ppv:'P2-OTHER'}).error,/并列/);assert.equal(p.status({...draft(s),enabled:true,end:at},Date.parse(at)),'已过期');});
test('disabled mapping remains required and cannot silently fall through normal PMS conversion',()=>{const s=p.seed();for(const r of s.rules.filter(r=>p.latest(r).category==='PHONE'))p.disableRule(s,r.id,r.revision,'停用','maintain',at);assert.match(p.evaluate(s,p.snapshot(s,ctx())).actual.errors.join(),/待补映射/);});

test('legacy channel fields cannot affect matching or make overlapping rules non-conflicting',()=>{const s=p.seed();s.rules[1].versions[0].channels=['OLD-A'];const c=ctx();c.channel='OLD-B';const snap=p.snapshot(s,c);assert.equal(Object.hasOwn(snap.context,'channel'),false);assert.equal(snap.rules.some(v=>Object.hasOwn(v,'channels')),false);assert.equal(p.evaluate(s,snap).actual.mapped[0].rule,'OMAP-0002 / V1');assert.deepEqual(s.rules[1].versions[0].channels,['OLD-A']);const r=p.saveRule(s,draft(s,{priority:10,channels:['OLD-B']}));assert.equal(Object.hasOwn(p.latest(r),'channels'),false);assert.throws(()=>p.enableRule(s,r.id,1,r.revision,'启用','maintain',at),/同优先级规则范围重叠/);});

test('catalog create, edit and delete enforce uniqueness, stable codes and optimistic versions',()=>{const s=p.seed(),x=newExtra(s,'泰国版'),code=x.code,rev=x.revision;assert.throws(()=>newExtra(s,'泰国版'),/不能重复/);p.saveExtra(s,{...x,name:'泰国版本'},code,rev);assert.equal(x.code,code);assert.throws(()=>p.saveExtra(s,{...x,name:'旧提交'},code,rev),/刷新/);p.deleteExtra(s,code,x.revision);assert.equal(p.catalogItems(s).some(x=>x.code===code),false);const next=newExtra(s,'泰国版本');assert.notEqual(next.code,code);assert.throws(()=>p.deleteExtra(s,next.code,next.revision,'view'),/查看权限/);});
test('every stored rule version blocks deletion and name edits preserve rules and publication facts',()=>{const s=p.seed(),x=s.extraCatalog.find(x=>x.code==='EXT-00001'),rules=p.clone(s.rules),old=p.clone(s.records);assert.ok(p.extraReferences(s,x.code).some(r=>r.status==='已替换'));assert.throws(()=>p.deleteExtra(s,x.code,x.revision),/OMAP-0001.*V1/);p.saveExtra(s,{...x,name:'马来版新名称'},x.code,x.revision);assert.deepEqual(s.rules,rules);assert.deepEqual(s.records,old);const r=p.saveRule(s,draft(s),s.rules[0].id,s.rules[0].revision);assert.equal(p.latest(r).details[0].name,'马来版新名称');assert.equal(r.versions[0].details[0].name,'马来版');});
test('rules require existing catalog values and concurrent new references block deletion',()=>{const s=p.seed(),x=newExtra(s,'泰国版'),rev=x.revision;const d=draft(s,{details:[{code:x.code,name:x.name,targetPpv:'P1-CN',models:[]}]});p.saveRule(s,d);assert.throws(()=>p.deleteExtra(s,x.code,rev),/草稿/);assert.throws(()=>p.saveRule(s,draft(s,{details:[{code:'',name:'随意填写',targetPpv:'P1-CN',models:[]}]})),/请选择已维护/);const y=newExtra(s,'临时值');p.deleteExtra(s,y.code,y.revision);assert.throws(()=>p.saveRule(s,draft(s,{details:[{code:y.code,name:y.name,targetPpv:'P1-CN',models:[]}]})),/已删除/);});
test('name-only extras can be reused while each rule still constrains primary targets and models',()=>{const s=p.seed(),x=p.saveExtra(s,{name:'国际版本'});assert.equal(x.category,undefined);const phone=draft(s,{details:[{code:x.code,name:x.name,targetPpv:'P1-CN',models:[]}]});assert.equal(p.validate(s,phone),'');const laptop={...p.clone(p.latest(s.rules[2])),details:[{code:x.code,name:x.name,targetPpv:'N1-US',models:[]}]};assert.equal(p.validate(s,laptop),'');assert.match(p.validate(s,{...laptop,details:[{...laptop.details[0],targetPpv:'P1-CN'}]}),/一级属性项/);assert.throws(()=>p.saveExtra(s,{name:' 国际版本 '}),/不能重复/);});
