const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
const base=process.env.PROTOTYPE_BASE_URL||'http://127.0.0.1:8795';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu']});const page=await browser.newPage({viewport:{width:1600,height:1100}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const close=()=>page.locator('#pmsMappingDialog [data-pms="close"]').first().click();
async function auction(p){if(!await p.locator('[data-nav="mappingRule"]').isVisible()){await p.locator('#systemSwitch').click();await p.locator('[data-system-option="auction"]').click();}await p.locator('[data-nav="mappingRule"]').click();}
async function enable(row){await row.locator('[data-pms="enable"]').click();await page.locator('#pmLifecycleReason').fill('验证后启用');await page.locator('[data-pms="lifecycle-save"]').click();}
try{
await page.addInitScript(()=>{if(!localStorage.getItem('fs-pms-special-attributes-v1'))localStorage.setItem('fs-pms-special-attributes-v1','{"preserved":true}');});
await page.goto(base+'/platform.html',{waitUntil:'networkidle'});await auction(page);
assert.equal(await page.locator('#pmsChannelFilter').count(),0);assert.match(await page.locator('#pmsRuleResults').innerText(),/购买渠道/);assert.deepEqual(await page.locator('#mappingRulePage [role="tab"]').allTextContents(),['规则配置','异常记录']);assert.equal(await page.locator('#pmsRuleResults tbody tr').count(),3);await page.screenshot({path:'/tmp/pms-unified-list.png',fullPage:true});
await page.locator('#mappingRulePage [data-pms="preview"]').click();assert.equal(await page.locator('#pvChannel').count(),0);assert.equal(await page.locator('[data-preview-extra="P2-OTHER"][data-group="actual"]').inputValue(),'');await page.locator('[data-pms="preview-run"]').click();assert.match(await page.locator('#pvOutput').innerText(),/未选择/);
await page.locator('[data-preview-extra="P2-OTHER"][data-group="actual"]').selectOption('EXT-00001');await page.locator('[data-preview-extra="P2-OTHER"][data-group="baseline"]').selectOption('EXT-00002');await page.locator('[data-pms="preview-run"]').click();assert.match(await page.locator('#pvOutput').innerText(),/OMAP-0002/);assert.match(await page.locator('#pvOutput').innerText(),/新加坡版/);assert.doesNotMatch(await page.locator('#pvOutput').innerText(),/停止该组取价/);await page.screenshot({path:'/tmp/pms-unified-preview.png'});await close();
await page.locator('[data-pms="tab"][data-id="records"]').click();await page.locator('[data-pms="record"]').first().click();await page.locator('[data-pms="retry"]').click();assert.match(await page.locator('#pmsMappingDialog').innerText(),/取价映射值失效/);await page.locator('[data-pms="reprocess"]').click();assert.match(await page.locator('#pmsMappingDialog').innerText(),/原明细/);await page.locator('[data-pms="reprocess-confirm"]').click();assert.match(await page.locator('#pmsMappingDialog h2').innerText(),/RUN-0002/);assert.doesNotMatch((await page.locator('#pmsMappingDialog .pms-version').allInnerTexts()).join(),/停止该组取价/);await close();
await page.locator('[data-pms="tab"][data-id="rules"]').click();let row=page.locator('#pmsRuleResults tbody tr').filter({hasText:'OMAP-0002'});await row.locator('[data-pms="edit"]').click();assert.equal(await page.locator('#pmChannelMode,#pmChannels,#pmGroups').count(),0);const detailModels=page.locator('[data-detail-models]').first();assert.equal(await detailModels.locator('option:checked').textContent(),'全部支持型号');await detailModels.selectOption('101');assert.equal(await detailModels.inputValue(),'101');await detailModels.selectOption(['__all','101']);assert.deepEqual(await detailModels.locator('option:checked').allTextContents(),['全部支持型号']);assert.equal(await page.locator('#pmCategory').inputValue(),'PHONE');assert.equal(await page.locator('#pmTrigger').inputValue(),'P2-OTHER');assert.equal(await page.locator('#pmDetailRows tbody tr').count(),2);assert.equal(await page.locator('#pmTrigger option').filter({hasText:'马来版'}).count(),0);
await page.locator('[data-pms="detail-add"]').click();const last=page.locator('[data-detail-row]').last();await last.locator('[data-detail-name]').fill('泰国版');await last.locator('[data-detail-target]').selectOption('P1-CN');await page.locator('#pmReason').fill('统一配置新增泰国附加选项');await page.locator('#pmDetailRows').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/pms-unified-editor.png'});await page.locator('[data-pms="save"]').click();assert.equal(await page.locator('#pmsMappingDialog').isVisible(),false);assert.match(await row.innerText(),/草稿/);assert.match(await row.innerText(),/当前生效 V1/);await enable(row);assert.match(await row.innerText(),/启用/);
await row.locator('[data-pms="history"]').click();assert.doesNotMatch(await page.locator('#pmsMappingDialog').innerText(),/渠道：/);assert.match(await page.locator('#pmsMappingDialog').innerText(),/全部支持型号/);assert.equal(await page.locator('#pmsMappingDialog .pms-version').count(),2);assert.match(await page.locator('#pmsMappingDialog .pms-version').first().innerText(),/泰国版/);assert.doesNotMatch(await page.locator('#pmsMappingDialog .pms-version').last().innerText(),/泰国版/);await close();
await page.locator('[data-pms="new"]').click();assert.equal(await page.locator('#pmChannelMode,#pmChannels,#pmGroups').count(),0);await page.locator('#pmName').fill('笔记本英国键盘配置');await page.locator('#pmCategory').selectOption('PHONE');await page.locator('#pmAttribute').selectOption('P2-CHANNEL');await page.locator('#pmTrigger').selectOption('P2-OTHER');await page.locator('#pmTargetAttribute').selectOption('P1-CHANNEL');await page.locator('[data-detail-name]').fill('马来版');await page.locator('[data-detail-target]').selectOption('P1-CN');await page.locator('#pmCategory').selectOption('LAPTOP');assert.equal(await page.locator('#pmAttribute').inputValue(),'');assert.equal(await page.locator('[data-detail-name]').inputValue(),'');assert.equal(await page.locator('[data-detail-target]').inputValue(),'');assert.equal(await page.locator('#pmModels input[value="101"]').count(),0);
await page.locator('#pmModelMode').selectOption('selected');await page.locator('#pmBrand').selectOption('Lenovo');assert.equal(await page.locator('#pmModels label[data-model="301"]').isVisible(),false);await page.locator('#pmModels input[value="302"]').check();await page.locator('#pmAttribute').selectOption('N2-KEYBOARD');await page.locator('#pmTrigger').selectOption('N2-OTHER');await page.locator('#pmTargetAttribute').selectOption('N1-KEYBOARD');await page.locator('[data-detail-name]').fill('英国键盘布局');await page.locator('[data-detail-target]').selectOption('N1-US');await page.locator('#pmPriority').fill('10');await page.locator('#pmReason').fill('按笔记本字典配置');await page.screenshot({path:'/tmp/pms-unified-laptop.png'});await page.locator('[data-pms="save"]').click();row=page.locator('#pmsRuleResults tbody tr').filter({hasText:'笔记本英国键盘配置'});await enable(row);assert.match(await row.innerText(),/笔记本/);assert.equal(await page.evaluate(()=>window.prototypeState.pmsMapping.getState().rules.find(r=>r.versions.at(-1).name==='笔记本英国键盘配置').versions.at(-1).details[0].models.length),0);
await page.reload({waitUntil:'networkidle'});await auction(page);assert.match(await page.locator('#pmsRuleResults').innerText(),/笔记本英国键盘配置/);assert.equal(await page.evaluate(()=>localStorage.getItem('fs-pms-special-attributes-v1')),'{"preserved":true}');
await page.locator('[data-pms="new"]').click();assert.equal(await page.locator('#pmChannelMode,#pmChannels,#pmGroups').count(),0);await page.locator('#pmName').fill('同优先级冲突检查');await page.locator('#pmCategory').selectOption('PHONE');await page.locator('#pmAttribute').selectOption('P2-CHANNEL');await page.locator('#pmTrigger').selectOption('P2-OTHER');await page.locator('#pmTargetAttribute').selectOption('P1-CHANNEL');await page.locator('[data-detail-name]').fill('欧洲版');await page.locator('[data-detail-target]').selectOption('P1-CN');await page.locator('#pmPriority').fill('10');await page.locator('#pmReason').fill('验证不同附加值也会冲突');await page.locator('[data-pms="save"]').click();await enable(page.locator('#pmsRuleResults tbody tr').filter({hasText:'同优先级冲突检查'}));assert.match(await page.locator('#pmsError').innerText(),/附加选项不同/);await close();
await page.locator('#pmsCategoryFilter').selectOption('LAPTOP');await page.locator('[data-pms="search"]').click();assert.doesNotMatch(await page.locator('#pmsRuleResults').innerText(),/iPhone/);await page.locator('[data-pms="reset"]').click();await page.locator('#pmsPermission').selectOption('view');assert.equal(await page.locator('[data-pms="new"]').count(),0);assert.equal(await page.locator('[data-pms="edit"]').count(),0);
// Compare unrelated pages against the exact same build with this module blocked.
const normalize=s=>s.replace(/ style=""/g,'');await page.locator('#systemSwitch').click();await page.locator('[data-system-option="b2b"]').click();await page.locator('[data-nav="list"]').click();await page.locator('[data-nav="store"]').click();const store=normalize(await page.locator('#storePage').innerHTML());await page.locator('[data-nav="list"]').click();const list=normalize(await page.locator('#listPage').innerHTML());
const baseline=await browser.newPage({viewport:{width:1600,height:1100}});await baseline.route('**/platform-pms-mapping.*',r=>r.abort());await baseline.goto(base+'/platform.html',{waitUntil:'networkidle'});await auction(baseline);await baseline.locator('#systemSwitch').click();await baseline.locator('[data-system-option="b2b"]').click();await baseline.locator('[data-nav="list"]').click();await baseline.locator('[data-nav="store"]').click();assert.equal(normalize(await baseline.locator('#storePage').innerHTML()),store);await baseline.locator('[data-nav="list"]').click();assert.equal(normalize(await baseline.locator('#listPage').innerHTML()),list);await baseline.close();
assert.deepEqual(errors,[]);console.log('PASS: unified rows, category linkage, previews, versions, conflicts, snapshots, permissions, persistence and unrelated pages');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
