const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../platform-price-management.js'),X=require('../vendor/xlsx-0.20.3.min.js'),M=require('../platform-pms-mapping.js');
const rows=(price=1200)=>[{'型号编码':'103','内存':'256GB','卖场':'新卖场','币种':'MYR','本地价格':price}];
test('Excel template round trips through real XLSX and maps rows',()=>{const b=P.templateWorkbook(X);assert.deepEqual(X.utils.sheet_to_json(b.Sheets[b.SheetNames[0]],{header:1})[0],P.headers);X.utils.sheet_add_aoa(b.Sheets[b.SheetNames[0]],[Object.values(rows()[0])],{origin:'A2'});const data=X.write(b,{type:'buffer',bookType:'xlsx'});const parsed=P.readWorkbook(X,data);assert.equal(parsed[0]['本地价格'],1200);assert.deepEqual(P.validateImport(parsed)[0].errors,[]);});
test('invalid import never mutates state; duplicate key includes normalized memory',()=>{const state=P.seed(),before=JSON.stringify(state);for(const patch of [{'型号编码':'UNKNOWN'},{'内存':'8GB'},{'卖场':''},{'币种':'CNY'},{'本地价格':0},{'本地价格':'abc'},{'本地价格':''}]){assert.throws(()=>P.importPrices(state,[{...rows()[0],...patch}],{name:'x'},'op','now'),/修正/);}assert.throws(()=>P.importPrices(state,[...rows(),{...rows()[0],'内存':'256'}],{name:'x'},'op','now'),/修正/);assert.equal(JSON.stringify(state),before);});
test('import upserts model and memory and freezes before/after evidence and file',()=>{const state=P.seed(),next=P.importPrices(state,rows(),{name:'new.xlsx',data:'data:test'},'op','now');assert.equal(state.prices[0].price,1000);assert.equal(next.prices.find(p=>p.modelId==='103').price,1200);assert.equal(next.prices.length,state.prices.length);assert.equal(next.batches[0].changes[0].before.price,1000);assert.equal(next.batches[0].changes[0].after.price,1200);assert.equal(next.batches[0].file.data,'data:test');assert.equal(next.batches[1].changes[0].after.price,1000);});
test('formula, no-strategy fallback, optional adjustments and no strategy stacking',()=>{let s=P.seed(),params={modelId:'103',memory:'256GB',actualP1:1600,baselineP1:2000};let r=P.calculate(s,params);assert.equal(r.coefficient,0.5);assert.equal(r.itemPrice,800);assert.equal(r.referencePrice,800);assert.equal(r.strategy,null);s=P.togglePolicy(s,s.policies[0].id,'op','now');r=P.calculate(s,params);assert.equal(r.referencePrice,740);s=P.savePolicy(s,{...P.blankPolicy(),priority:1,ranges:[{min:0,max:null,rate:10,fixed:0}]},null,'op','now');s=P.togglePolicy(s,s.policies[0].id,'op','now');assert.equal(P.calculate(s,params).referencePrice,880);assert.throws(()=>P.calculate(s,{...params,baselineP1:0}),/基准/);assert.throws(()=>P.calculate(s,{...params,actualP1:NaN}),/本机/);assert.throws(()=>P.calculate(s,{...params,memory:'512GB'}),/缺少/);});
test('strategy scope, versions, interval boundaries, overlap and disabled state',()=>{let s=P.seed(),old=s.policies[0];s=P.togglePolicy(s,old.id,'op','first');s=P.savePolicy(s,{...P.blankPolicy(),priority:10,ranges:[{min:500,max:1500,rate:1,fixed:0}]},null,'op','now');assert.throws(()=>P.togglePolicy(s,s.policies[0].id,'op','now'),/重叠/);const draft={...old,ranges:[{min:0,max:2000,rate:1,fixed:0}]};s=P.savePolicy(s,draft,old.id,'op','edit');const current=s.policies.find(p=>p.id===old.id);assert.equal(current.version,2);assert.equal(current.status,'停用');assert.equal(current.history[0].ranges[0].max,1000);assert.equal(current.history[0].status,'启用');assert.match(P.validatePolicy({...P.blankPolicy(),category:'LAPTOP',modelMode:'selected',modelIds:['103']}),/型号/);assert.match(P.validatePolicy({...P.blankPolicy(),ranges:[{min:5,max:5,rate:0,fixed:0}]}),/区间/);assert.match(P.validatePolicy({...P.blankPolicy(),ranges:[]}),/至少/);});
test('primary conversion saves without rule name or notes while extra value still needs a name',()=>{const s=M.seed(),r=s.rules[0],draft=M.clone(M.latest(r));delete draft.name;delete draft.reason;draft.priority=90;assert.equal(M.validate(s,draft),'');const saved=M.saveRule(s,draft,r.id,r.revision);assert.equal(M.latest(saved).priority,90);assert.throws(()=>M.saveExtra(s,{country:'MY',category:'PHONE',sourceStandard:'DEMO-PHONE-L2',sourcePpn:'P2-CHANNEL',triggerPpv:'P2-OTHER',name:''}),/名称/);});

test('multiple ranges select only one row at boundaries and preserve no-match fallback',()=>{let s=P.seed();s=P.togglePolicy(s,s.policies[0].id,'op','now');const calc=item=>P.calculate(s,{modelId:'103',memory:'256GB',actualP1:item,baselineP1:1000});assert.equal(calc(999.99).matchedRange.index,0);assert.equal(calc(1000).matchedRange.index,1);assert.equal(calc(1000).referencePrice,930);assert.equal(calc(3000).matchedRange.index,2);assert.equal(calc(3000).referencePrice,2860);const p=s.policies[0];p.ranges=[{min:0,max:1000,rate:6,fixed:0},{min:2000,max:3000,rate:5,fixed:20}];assert.equal(calc(1500).strategy,null);assert.equal(calc(1500).referencePrice,1500);p.ranges.push({min:500,max:900,rate:4,fixed:5});assert.match(P.validatePolicy(p),/第1行与第3行.*重叠/);assert.throws(()=>calc(600),/多个价格区间/);});
test('range validation rejects missing amounts, overlap, and unbounded rows before later rows',()=>{const p=P.blankPolicy();for(const row of [{min:0,max:null,fixed:NaN,rate:0},{min:0,max:null,fixed:0,rate:NaN},{min:0,max:0,fixed:0,rate:0}])assert.notEqual(P.validatePolicy({...p,ranges:[row]}),'');assert.match(P.validatePolicy({...p,ranges:[{min:0,max:null,rate:0,fixed:0},{min:100,max:200,rate:0,fixed:0}]}),/重叠/);assert.equal(P.validatePolicy({...p,ranges:[{min:100,max:200,rate:0,fixed:0},{min:0,max:100,rate:0,fixed:0}]}),'');});
test('legacy single-range configurations retain calculation and immutable history on editing',()=>{let s=P.seed();const legacy={...s.policies[0],min:500,max:1500,rateOn:true,rate:-5,fixedOn:true,fixed:-20,status:'启用'};delete legacy.ranges;s.policies=[legacy];const before=JSON.stringify(s);assert.equal(P.calculate(s,{modelId:'103',memory:'256GB',actualP1:1600,baselineP1:2000}).referencePrice,740);assert.equal(JSON.stringify(s),before);const next=P.savePolicy(s,{...legacy,ranges:[...P.policyRanges(legacy),{min:1500,max:null,rate:-2,fixed:0}]},legacy.id,'op','now');assert.deepEqual(next.policies[0].history[0].min,500);assert.equal(next.policies[0].history[0].ranges,undefined);assert.equal(next.policies[0].ranges.length,2);assert.equal(JSON.stringify(s),before);});
test('price-source column is absent from new templates and ignored in legacy uploads',()=>{assert.equal(P.headers.includes('价格来源'),false);const parsed=P.validateImport([{...rows()[0],'价格来源':'旧来源'}]);assert.equal(Object.hasOwn(parsed[0],'source'),false);});
