const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM,VirtualConsole}=require(process.env.JSDOM_MODULE||'/tmp/order-audit-dom/node_modules/jsdom');
(async()=>{const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=await JSDOM.fromURL('http://127.0.0.1:8796/quote-config.html',{resources:'usable',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};}});const w=dom.window,d=w.document;await new Promise(r=>w.addEventListener('load',r));const el=s=>{const x=d.querySelector(s);assert.ok(x,s);return x;},click=s=>el(s).click(),input=(s,v)=>{el(s).value=v;el(s).dispatchEvent(new w.Event('input',{bubbles:true}));},change=(s,v)=>{el(s).value=v;el(s).dispatchEvent(new w.Event('change',{bubbles:true}));};
click('[data-action="edit"]');input('[data-row="1"] [data-field="minutes"]','10');click('[data-action="save"]');assert.match(el('#error').textContent,/重复/);click('[data-action="close"]');
click('[data-action="tab"][data-tab="demo"]');click('[data-action="start"]');click('[data-action="confirm-start"]');assert.equal(d.querySelectorAll('.bid-event').length,0);click('[data-action="next"]');assert.equal(d.querySelectorAll('.bid-event').length,1);assert.equal(d.querySelectorAll('.dot').length,1);assert.match(el('.big-price').textContent,/1,700/);click('[data-action="accept"]');click('[data-action="next"]');click('[data-action="confirm-accept"]');assert.match(el('#error').textContent,/已更新/);click('[data-action="close"]');click('[data-action="accept"]');click('[data-action="confirm-accept"]');assert.match(el('.big-price').textContent,/1,900/);assert.equal(el('[data-action="next"]').disabled,true);assert.equal(d.querySelectorAll('.bid-event').length,2);
click('[data-action="reset-round"]');click('[data-action="confirm-reset"]');for(let i=0;i<8;i++)click('[data-action="advance"]');click('[data-action="start"]');click('[data-action="confirm-start"]');assert.equal(d.querySelectorAll('.bid-event').length,1);assert.match(el('.big-price').textContent,/1,900/);
click('[data-action="tab"][data-tab="rules"]');click('[data-action="edit"]');input('[data-row="0"] [data-field="percent"]','80');click('[data-action="save"]');assert.match(el('#app').textContent,/v2/);click('[data-action="history"]');assert.match(el('#dialog').textContent,/85%/);click('[data-action="close"]');click('[data-action="tab"][data-tab="demo"]');assert.match(el('.operator').textContent,/85%/);assert.match(el('.operator').textContent,/v1/);change('#permission','view');assert.equal(el('[data-action="stop"]').disabled,true);click('[data-action="tab"][data-tab="rules"]');assert.equal(el('[data-action="new"]').disabled,true);
assert.deepEqual(errors,[]);dom.window.close();
// Verify the platform menu extension against the actual setView contract without loading unrelated modules.
const host=new JSDOM('<div id="crumbGroup"></div><div id="crumbCurrent"></div><div data-nav="roundList"></div><section id="roundListPage" class="page active"></section>',{url:'https://example.test/platform.html#quoteConfig',runScripts:'outside-only'});host.window.setView=v=>{host.window.document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===v+'Page'));};host.window.eval(fs.readFileSync('platform-quote-config.js','utf8'));assert.ok(host.window.document.querySelector('#quoteConfigPage.active'));assert.equal(host.window.document.querySelector('iframe').getAttribute('src'),'quote-config.html?embed=1');assert.equal(host.window.document.querySelector('#crumbCurrent').textContent,'报价配置');host.window.close();
console.log('PASS: editor validation, map single bidder, staged offers, acceptance race, early settlement, late start, version isolation, read-only permissions and platform menu');})().catch(e=>{console.error(e);process.exit(1);});
