const assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_MODULE||'/tmp/order-audit-dom/node_modules/jsdom');
(async()=>{const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const legacy=JSON.stringify({schema:1,state:{policies:[{id:'STEP-00001',version:4,rows:[{minutes:10,percent:85}],history:[]}]}});
const dom=await JSDOM.fromURL('http://127.0.0.1:8796/quote-config.html',{resources:'usable',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.localStorage.setItem('fs-quote-config-demo-v1',legacy);}});const w=dom.window,d=w.document;await new Promise(r=>w.addEventListener('load',r));
const el=s=>{const x=d.querySelector(s);assert.ok(x,s);return x;},click=s=>el(s).click(),input=(s,v)=>{el(s).value=v;el(s).dispatchEvent(new w.Event('input',{bubbles:true}));},change=(s,v)=>{el(s).value=v;el(s).dispatchEvent(new w.Event('change',{bubbles:true}));};
assert.equal(d.querySelectorAll('[data-row]').length,3);input('#preview-cap','3000');assert.match(el('[data-row="0"] .preview-amount').textContent,/2,550/);assert.equal(d.querySelector('dialog,.map,.metrics,.explainer,.tabs,.operator'),null);
for(const removed of ['流程演示','最后一档必须','当前生效策略','生效策略档位','最高出价比例','操盘手控制台'])assert.ok(!d.body.textContent.includes(removed),removed);
for(const label of ['竞拍剩余时间比例','首次出价比例','出价次数','包含首次出价的总次数'])assert.ok(d.body.textContent.includes(label));
input('[data-row="0"] [data-field="remainingPercent"]','101');click('[data-action="save"]');assert.match(el('#error').textContent,/竞拍剩余时间比例/);click('[data-action="restore"]');
input('[data-row="0"] [data-field="bidCount"]','1.5');click('[data-action="save"]');assert.match(el('#error').textContent,/正整数/);input('[data-row="0"] [data-field="bidCount"]','6');change('#enabled','true');click('[data-action="save"]');assert.match(el('.version').textContent,/v2/);assert.equal(el('#enabled').value,'true');assert.equal(el('[data-row="2"] [data-field="firstBidPercent"]').value,'95');
assert.equal(w.localStorage.getItem('fs-quote-config-demo-v1'),legacy);const persisted=JSON.parse(w.localStorage.getItem('fs-quote-config-v2'));assert.equal(persisted.current.rows[0].bidCount,6);
click('[data-action="add"]');assert.equal(d.querySelectorAll('[data-row]').length,4);click('[data-action="save"]');assert.match(el('#error').textContent,/第4行/);click('[data-action="remove"][data-index="3"]');
input('[data-row="0"] [data-field="bidCount"]','8');click('[data-action="history"]');assert.equal(el('[data-row="0"] [data-field="bidCount"]').value,'8');assert.ok(d.querySelector('.history-card'));assert.match(el('.history-card').textContent,/旧版分钟配置/);click('[data-action="restore"]');assert.equal(el('[data-row="0"] [data-field="bidCount"]').value,'6');
// Merchant directory stays isolated from quotation rules and retains unsaved inputs across tabs.
input('[data-row="0"] [data-field="bidCount"]','9');click('#merchants-tab');assert.equal(el('#app').hidden,true);assert.equal(el('#merchants-panel').hidden,false);
click('[data-merchant-action="new"]');
const submitMerchant=()=>el('#merchant-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
submitMerchant();assert.match(el('#merchant-error').textContent,/商家名称/);
input('[name="name"]','<b>测试商家</b>');
assert.equal(el('#merchant-address-parts-country').value,'马来西亚');assert.equal(el('#merchant-address-parts-longitude').readOnly,true);assert.equal(el('#merchant-address-parts-latitude').readOnly,true);
input('#merchant-address-parts-search','unmatched-address');assert.match(el('[data-search-status]').textContent,/未找到匹配地址/);
input('#merchant-address-parts-search','Tower');click('.shop-address-results button');assert.equal(el('#merchant-address-parts-longitude').value,'101.711600');assert.equal(el('#merchant-address-parts-latitude').value,'3.157800');assert.equal(el('#merchant-address-parts-city').value,'Kuala Lumpur');
input('#merchant-address-parts-postcode','1234');submitMerchant();assert.match(el('#merchant-error').textContent,/5 位数字/);
input('#merchant-address-parts-postcode','50450');submitMerchant();assert.match(el('#merchant-error').textContent,/获取对应坐标/);
input('#merchant-address-parts-search','Tower');click('.shop-address-results button');
click('#rules-tab');assert.equal(el('[data-row="0"] [data-field="bidCount"]').value,'9');click('#merchants-tab');assert.equal(el('#merchant-address-parts-detail').value,'Demo Tower, 12 Jalan Contoh');
change('#permission','view');assert.equal(el('#merchant-address-parts-search').disabled,true);change('#permission','edit');assert.equal(el('#merchant-address-parts-longitude').value,'101.711600');submitMerchant();
assert.equal(d.querySelector('#merchant-form'),null);assert.match(el('.merchant-table').textContent,/<b>测试商家<\/b>/);assert.equal(d.querySelector('.merchant-table tbody b'),null);
const merchantSaved=w.localStorage.getItem('fs-quote-merchants-v1');assert.equal(JSON.parse(merchantSaved).length,1);assert.equal(JSON.parse(merchantSaved)[0].addressParts.placeId,'demo-kl');assert.equal(w.localStorage.getItem('fs-shop-address-v1'),null);assert.deepEqual(JSON.parse(w.localStorage.getItem('fs-quote-config-v2')),persisted);
const reloaded=await JSDOM.fromURL('http://127.0.0.1:8796/quote-config.html',{resources:'usable',runScripts:'dangerously',beforeParse(rw){rw.localStorage.setItem('fs-quote-merchants-v1',merchantSaved);}});await new Promise(r=>reloaded.window.addEventListener('load',r));assert.match(reloaded.window.document.querySelector('.merchant-table').textContent,/101.7116/);reloaded.window.close();
click('[data-merchant-action="delete"]');click('[data-merchant-action="keep"]');assert.equal(JSON.parse(w.localStorage.getItem('fs-quote-merchants-v1')).length,1);
change('#permission','view');assert.equal(el('[data-merchant-action="new"]').disabled,true);assert.equal(el('[data-merchant-action="delete"]').disabled,true);
change('#permission','edit');click('[data-merchant-action="delete"]');click('[data-merchant-action="confirm-delete"]');assert.equal(JSON.parse(w.localStorage.getItem('fs-quote-merchants-v1')).length,0);assert.match(el('.merchant-table').textContent,/暂无报价商家/);
click('#rules-tab');assert.equal(el('[data-row="0"] [data-field="bidCount"]').value,'9');click('[data-action="restore"]');
change('#permission','view');assert.equal(el('[data-action="save"]').disabled,true);assert.equal(el('[data-row="0"] input').disabled,true);
assert.deepEqual(errors,[]);dom.window.close();
const host=new JSDOM('<div id="crumbGroup"></div><div id="crumbCurrent"></div><div data-nav="roundList"></div><section id="roundListPage" class="page active"></section>',{url:'https://example.test/platform.html#quoteConfig',runScripts:'outside-only'});host.window.setView=v=>{host.window.document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===v+'Page'));};host.window.eval(fs.readFileSync('platform-quote-config.js','utf8'));assert.ok(host.window.document.querySelector('#quoteConfigPage.active'));assert.match(host.window.document.querySelector('iframe').getAttribute('src'),/quote-config.html\?embed=1/);host.window.close();
console.log('PASS: inline form, removed views, new ratio/count fields, validation, save/restore, version history, legacy preservation and permissions');})().catch(e=>{console.error(e);process.exit(1);});
