const test=require('node:test'),assert=require('node:assert/strict'),R=require('../platform-report2-rules.js');
test('model scope constrains primary attributes for every selected model',()=>{let r=R.seeds()[1];assert.equal(R.validate(r),'');r.modelMode='all';assert.match(R.validate(r),/不适用/);r.category='LAPTOP';assert.match(R.validate(r),/不适用/);});
test('rejects empty conditions, invalid targets and non-integer priorities',()=>{let r=R.seeds()[0];for(const p of [0,-1,1.5,Infinity])assert.match(R.validate({...r,priority:p}),/正整数/);assert.match(R.validate({...r,conditions:[]}),/至少/);assert.match(R.validate({...r,targets:[...r.targets,R.row('DEMO-P1-BOARD','ORIGINAL')]}),/一个目标属性项/);});
test('edits preserve immutable prior configuration and hit records',()=>{const original=R.seeds()[0];original.hits=[{report:'R2-DEMO',version:1}];const before=JSON.stringify(original),draft={...original,name:'Changed',priority:2};delete draft.history;delete draft.logs;delete draft.hits;const changed=R.revise(original,draft,'Operator','2026-09-16','调整规则');assert.equal(JSON.stringify(original),before);assert.equal(changed.version,2);assert.equal(changed.history[0].name,original.name);assert.equal(changed.history[0].priority,10);assert.deepEqual(changed.hits,original.hits);assert.equal(changed.logs.at(-1).reason,'调整规则');});

test('one rule requires exactly one target while retaining all AND conditions',()=>{const r=R.seeds()[1];assert.equal(r.conditions.length,2);assert.equal(r.targets.length,1);assert.equal(R.validate(r),'');assert.match(R.validate({...r,targets:[]}),/一个目标/);assert.match(R.validate({...r,targets:[...r.targets,R.row('DEMO-P1-BATTERY','REPLACED')]}),/一个目标/);});
test('explicit legacy split keeps original targets and history, with disabled single-target children',()=>{const records=R.seeds(),old=records[1];old.targets.push(R.row('DEMO-P1-BATTERY','REPLACED'));old.status='启用';old.hits=[{report:'old-hit'}];old.history=[{version:0}];const before=JSON.stringify(records);assert.doesNotThrow(()=>R.splitRule(records,old.id,'op','now',''));const next=R.splitRule(records,old.id,'op','now','拆分目标');assert.equal(JSON.stringify(records),before);const preserved=next.find(r=>r.id===old.id);assert.equal(preserved.status,'停用');assert.deepEqual(preserved.targets,old.targets);assert.deepEqual(preserved.history,old.history);assert.deepEqual(preserved.hits,old.hits);assert.equal(preserved.splitInto.length,2);const children=preserved.splitInto.map(id=>next.find(r=>r.id===id));assert.equal(new Set(next.map(r=>r.id)).size,next.length);for(const child of children){assert.equal(child.targets.length,1);assert.equal(child.status,'停用');assert.deepEqual(child.conditions,old.conditions);assert.deepEqual(child.modelIds,old.modelIds);assert.equal(child.priority,old.priority);assert.equal(R.validate(child),'');assert.equal(child.splitFrom.id,old.id);}assert.throws(()=>R.splitRule(next,old.id,'op','now','再次拆分'),/已完成/);});

test('rule name and reason are not required',()=>{const r=R.seeds()[0];delete r.name;delete r.reason;assert.equal(R.validate(r),'');assert.equal(R.revise(r,{...r,priority:4},'op','now').priority,4);});
