const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--disable-gpu'],executablePath:process.env.CHROMIUM_PATH});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let dialogs=0;page.on('dialog',async d=>{dialogs++;await d.dismiss()});const base=process.env.PROTOTYPE_BASE_URL||'http://localhost:8778';
try{for(const portal of ['platform','store']){
await page.goto(base+'/'+portal+'.html',{waitUntil:'domcontentloaded'});
await page.evaluate(portal=>{if(portal==='platform'){setView('store');openNewStoreModal()}else{roleSwitch.value='merchant';renderProfileScope();prototypeState.editManagedStore()}},portal);
const prefix=portal==='platform'?'newStoreAddress-parts-':'managed-address-parts-',field=k=>page.locator('#'+prefix+k);
assert.equal(await field('latitude').inputValue(),'');assert.equal(await field('longitude').getAttribute('readonly'),'');assert.equal(await field('state').evaluate(e=>e.tagName),'INPUT');
await field('search').fill('Demo Garden');await page.locator('.shop-address-results button').first().click();assert.equal(await field('latitude').inputValue(),'3.157900');assert.equal(await field('state').inputValue(),'Selangor');
await field('search').fill('Demo Tower');assert.equal(await field('latitude').inputValue(),'3.157900');assert.equal(await field('detail').inputValue(),'Demo Garden, 18 Jalan Contoh');await page.locator('.shop-address-results button').first().click();assert.equal(await field('longitude').inputValue(),'101.711600');assert.equal(await field('state').inputValue(),'W.P. Kuala Lumpur');assert.equal(await field('city').inputValue(),'Kuala Lumpur');assert.equal(await field('postcode').inputValue(),'50450');assert.equal(dialogs,0);const before=await page.locator('.shop-address input').evaluateAll(es=>es.filter(e=>!e.id.endsWith('-search')).map(e=>e.value));await field('search').fill('no-match-address');assert.equal(await page.locator('.shop-address-results').isVisible(),false);assert.deepEqual(await page.locator('.shop-address input').evaluateAll(es=>es.filter(e=>!e.id.endsWith('-search')).map(e=>e.value)),before);await field('search').fill('');
if(portal==='platform'){
await page.locator('#newStoreName').fill('Coordinate Shop');await page.locator('#newStorePhone').fill('+60123456789');await page.locator('#newStoreBankHolder').fill('Test');await page.locator('#newStoreBankName').fill('Maybank');await page.locator('#newStoreBankNumber').fill('123456781234');await page.screenshot({path:'/tmp/shop-coordinates-pc.png',fullPage:true});await page.locator('#saveStore').click();assert.equal(await page.evaluate(()=>stores.at(-1).addressParts.latitude),3.1578);await page.evaluate(()=>openStoreDetail(stores.at(-1)));assert.ok((await page.locator('#storeDetailBody').innerText()).includes('101.711600'));await page.evaluate(()=>openStoreEditor(stores.at(-1)));assert.equal(await page.locator('#editStoreAddress-parts-latitude').inputValue(),'3.157800');await page.locator('#editStoreAddress-parts-detail').fill('Manual changed street');assert.equal(await page.locator('#editStoreAddress-parts-latitude').inputValue(),'');await page.locator('#businessConfirmBtn').click();assert.equal(await page.evaluate(()=>stores.at(-1).addressParts.latitude),null);
}else{
await page.setViewportSize({width:430,height:932});await page.locator('#managed-name').fill('App Coordinate Shop');await page.locator('#managed-holder').fill('Test');await page.locator('#managed-bankName').fill('Maybank');await page.locator('#managed-number').fill('123456781234');await page.screenshot({path:'/tmp/shop-coordinates-app.png',fullPage:true});await page.locator('#saveManagedStore').click();const id=await page.evaluate(()=>storeProfiles.at(-1).id);await page.reload({waitUntil:'domcontentloaded'});await page.evaluate(id=>{roleSwitch.value='merchant';renderProfileScope();prototypeState.editManagedStore(id)},id);assert.equal(await field('longitude').inputValue(),'101.711600');await field('city').fill('Other city');assert.equal(await field('longitude').inputValue(),'');}
}assert.deepEqual(errors,[]);console.log('PASS: PC/App read-only coordinates, automatic replacement, invalidation, save/reopen and detail display');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
