const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--disable-gpu'],executablePath:process.env.CHROMIUM_PATH});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});const base=process.env.PROTOTYPE_BASE_URL||'http://localhost:8778';
try{
await page.goto(base+'/platform.html',{waitUntil:'domcontentloaded'});console.log('PC loaded');await page.evaluate(()=>{setView('store');openNewStoreModal()});console.log('PC form opened');
assert.equal(await page.locator('#newStoreAddress-parts-country').inputValue(),'马来西亚');assert.equal(await page.locator('#newStoreAddress-parts-state').inputValue(),'');
await page.locator('#newStoreMerchant').selectOption('M1003');assert.equal(await page.locator('#newStoreAddress-parts-state').inputValue(),'Selangor');assert.equal(await page.locator('#newStoreAddress-parts-postcode').inputValue(),'47300');
await page.screenshot({path:'/tmp/shop-address-pc.png',fullPage:true});
page.once('dialog',d=>d.dismiss());await page.locator('#newStoreMerchant').selectOption('M1002');assert.equal(await page.locator('#newStoreMerchant').inputValue(),'M1003');
page.once('dialog',d=>d.accept());await page.locator('#newStoreMerchant').selectOption('M1002');assert.equal(await page.locator('#newStoreAddress-parts-city').inputValue(),'');
await page.locator('#newStoreAddress-parts-detail').fill('Demo');await page.locator('.shop-address-results button').first().click();assert.equal(await page.locator('#newStoreAddress-parts-state').inputValue(),'Selangor');
await page.locator('#newStoreName').fill('Address Test Shop');await page.locator('#newStorePhone').fill('+60123456789');await page.locator('#newStoreBankHolder').fill('Test');await page.locator('#newStoreBankName').fill('Maybank');await page.locator('#newStoreBankNumber').fill('123456789012');
await page.locator('#newStoreAddress-parts-postcode').fill('1234');await page.locator('#saveStore').click();assert.equal(await page.locator('#storeError').isVisible(),true);await page.locator('#newStoreAddress-parts-postcode').fill('01234');await page.locator('#saveStore').click();
assert.equal(await page.evaluate(()=>stores.at(-1).addressParts.postcode),'01234');assert.equal(await page.evaluate(()=>stores.at(-1).city),'Petaling Jaya');
await page.evaluate(()=>{users.find(u=>u.merchantId==='M1002').kyc='已认证';users.find(u=>u.merchantId==='M1002').kycAddress={country:'MY',state:'Johor',city:'JB',postcode:'80000',detail:'KYC Changed'};openStoreEditor(stores.at(-1))});assert.equal(await page.locator('#editStoreAddress-parts-state').inputValue(),'Selangor');
await page.locator('#editStoreAddress-parts-detail').fill('Saved manual detail');await page.locator('#businessConfirmBtn').click();assert.equal(await page.evaluate(()=>stores.at(-1).addressParts.detail),'Saved manual detail');
await page.evaluate(()=>{closeModals();openStoreEditor(stores.at(-1))});await page.locator('#editStoreAddress-parts-detail').fill('cancelled');await page.evaluate(()=>closeModals());assert.equal(await page.evaluate(()=>stores.at(-1).addressParts.detail),'Saved manual detail');
// Shared-bank path must validate and preserve the address just like independent mode.
await page.evaluate(()=>{MerchantBanks.save('M1003',{holder:'Fixture',bankName:'CIMB',accountNumber:'555555551234'},null,'test');openNewStoreModal()});await page.locator('#newStoreMerchant').selectOption('M1003');await page.locator('#newStoreName').fill('Shared Address Shop');await page.locator('#newStorePhone').fill('+60123456789');await page.locator('#newStoreBankMode').selectOption('merchant');await page.locator('#newMerchantBank').selectOption({index:1});await page.locator('#saveStore').click();assert.equal(await page.evaluate(()=>stores.at(-1).addressParts.state),'Selangor');
await page.goto(base+'/store.html',{waitUntil:'domcontentloaded'});await page.setViewportSize({width:430,height:932});await page.evaluate(()=>{roleSwitch.value='merchant';renderProfileScope();prototypeState.editManagedStore()});
assert.equal(await page.locator('#managed-useVerifiedAddress').count(),0);assert.equal(await page.locator('#managed-address-parts-country').inputValue(),'马来西亚');assert.equal(await page.locator('#managed-address-parts-city').inputValue(),'');
await page.locator('#managed-name').fill('App address shop');await page.locator('#managed-address-parts-state').selectOption('Selangor');await page.locator('#managed-address-parts-city').fill('Petaling Jaya');await page.locator('#managed-address-parts-postcode').fill('47810');await page.locator('#managed-address-parts-detail').fill('18 Jalan Sample, Unit 2');await page.locator('#managed-holder').fill('Test');await page.locator('#managed-bankName').fill('Maybank');await page.locator('#managed-number').fill('123456781234');await page.screenshot({path:'/tmp/shop-address-app.png',fullPage:true});await page.locator('#saveManagedStore').click();assert.equal(await page.evaluate(()=>storeProfiles.at(-1).addressParts.city),'Petaling Jaya');const id=await page.evaluate(()=>storeProfiles.at(-1).id);
await page.reload({waitUntil:'domcontentloaded'});await page.evaluate(id=>{roleSwitch.value='merchant';renderProfileScope();prototypeState.editManagedStore(id)},id);assert.equal(await page.locator('#managed-address-parts-detail').inputValue(),'18 Jalan Sample, Unit 2');
await page.locator('#managed-address-parts-postcode').fill('1234');await page.locator('#saveManagedStore').click();assert.equal(await page.locator('#managed-error').isVisible(),true);
await page.evaluate(()=>{roleSwitch.value='employee';renderProfileScope()});assert.equal(await page.locator('#managedStoreEditPage').isVisible(),false);
assert.deepEqual(errors,[]);console.log('PASS: PC/App address defaults, optional KYC, search, invalid postcode, save, edit, cancel, bank paths, reload and role guard');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
