const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox','--disable-gpu','--single-process','--no-zygote']});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.PROTOTYPE_BASE_URL||'http://127.0.0.1:8794')+'/store.html');
const role=async r=>p.evaluate(r=>{document.querySelector('#roleSwitch').value=r;document.querySelector('#roleSwitch').dispatchEvent(new Event('change'));showPage('bills');},r);
const open=async id=>{await p.locator('[data-earning-id="'+id+'"] summary').click();await p.locator('[data-earning-order="'+id+'"]').click();};const labels=()=>p.locator('#earningsOrderDialog .summary-row span').allTextContents();const close=()=>p.locator('#earningsOrderDialog button').click();
await role('employee');assert.equal(await p.locator('[data-earning-id]').count(),1);await open('FSO-260909-0101');assert.deepEqual(await labels(),['订单成交金额','卖家应得金额','店员分成']);assert.deepEqual(await p.locator('#earningsOrderDialog strong').allTextContents(),['MYR 2,410.00','MYR 2,152.40','MYR 42.00']);assert.doesNotMatch(await p.locator('#earningsOrderDialog').innerHTML(),/门店分成|平台分成|Store share/);await p.screenshot({path:'/tmp/employee-earning-order.png'});await close();assert.match(await p.locator('#earningsRows').innerText(),/MYR 37.00/);
await role('merchant');await open('FSO-260909-0101');assert.deepEqual(await labels(),['订单成交金额','卖家应得金额','店员分成','门店分成']);assert.match(await p.locator('#earningsOrderDialog').innerText(),/MYR 180.00/);assert.doesNotMatch(await p.locator('#earningsOrderDialog').innerText(),/平台分成/);await p.screenshot({path:'/tmp/merchant-earning-order.png'});
await role('employee');assert.equal(await p.locator('#earningsOrderDialog').isVisible(),false);assert.equal(await p.locator('#earningsOrderDialog').innerHTML(),'');await open('FSO-260909-0101');assert.equal((await labels()).length,3);await close();
await role('merchant');await p.locator('[data-earning-kind="commission"]').click();await open('FSO-260907-0103');assert.equal((await labels()).length,4);assert.match(await p.locator('#earningsOrderDialog').innerText(),/MYR 64.50/);await close();await p.locator('[data-earning-status="settled"]').click();await p.locator('#earningsCurrency').selectOption('HKD');await open('FSO-260905-0105');assert.match(await p.locator('#earningsOrderDialog').innerText(),/HKD 5,100.00/);assert.doesNotMatch(await p.locator('#earningsOrderDialog').innerText(),/MYR/);await close();
await p.evaluate(()=>applyLanguage('en'));await p.evaluate(()=>renderEarnings());await open('FSO-260905-0105');assert.deepEqual(await labels(),['Order transaction amount','Seller proceeds','Staff share','Store share']);assert.deepEqual(errors,[]);console.log('PASS employee/merchant field isolation, original amounts vs adjusted earnings, merchant commission tab, MYR/HKD, English and role-change stale dialog clearing.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
